### ISSUE TITLE
M3U8 Suggestion

### ISSUE THREAD

**Issue by ooftv** [Fleker/CumulusTV#1]
http://pablogott.videocdn.scaleengine.net/pablogott-iphone/play/ooftv1/playlist.m3u8

24/7 Music videos from the California garage scene

**Comment by Fleker** [comment]
Thanks for the suggestion. I'll add it in the next commit

**Comment by Fleker** [comment]
Added in f9ad5bf01e06213a9aca1ada04cff4e0eb75796a

**Comment by Fleker** [comment]
Hey, is there a specific thumbnail that you'd like me to include? Right now I'm using your GitHub avatar.

**Comment by ooftv** [comment]
That one is good, here's a bigger version:
http://imgur.com/QRCIhN4

We're called OutOfFocus.TV or just OOFTV
