### ISSUE TITLE
local stream problems

### ISSUE THREAD

**Issue by kartajan** [Fleker/CumulusTV#100]
I have an HDMI Encoder that I am trying to connect via CumulusTV to 3 Android TV Boxes (Shield x2, NP x1)

I cannot seem to get a successful stream to play. I am getting good playback on VLC. (HTTP Stream)

HW specs here: http://www.amazon.com/OPR-NH100-Encoder-Broadcast-Recording-replace/dp/B00NIFJYEC/ref=sr_1_1?ie=UTF8&qid=1455739868&sr=8-1&keywords=hdmi+encoder

**Comment by Fleker** [comment]
Hmm the product listing seems to mention VLC decoding, which makes me think that there's some sort of custom software decoding that they're doing which I'm not doing. I don't have one of these so I can't really say what the best solution is right now.

**Comment by kartajan** [comment]
Protocol: HTTP UDP unicast / multicast;RTSP;RTMP

The black screen I get from this in CumulusTV is also present on several of the stream sources that were included on the app, so I am guessing that something with the latest android security updates broke something???

**Comment by Fleker** [comment]
No clue why it's being weird, as it works well for me. Although I'm
releasing a big update soon which I'd like you to check.

I don't know if rtsp is supported.

**Comment by kartajan** [comment]
will do,

**Comment by kartajan** [comment]
Still the same problem. This is the info for the stream I am trying to play - Please advise me as to what I can try....

http://192.168.0.150:80/hdmi

Codec Information
Stream 0
 Type: Video
 Original ID: 68
 Codec: H264 - MPEG4 AVC (part 10) (h264)
 Resolution: 1920x1080
 Decoded Format: Planar 4:2:0 YUV
Stream 1
 Type: Audio
 Original ID: 69
 Code: MPEG AAC Audio (mp4a)
 Channels: Stereo
 Sample Rate: 44100 Hz



________________________________

**Comment by Fleker** [comment]
It looks like the stream should play correctly. I don't really know why
not.

**Comment by kartajan** [comment]
any ideas on what I could try in order to determine the issue?

**Comment by kartajan** [comment]
Is this the problem, and if so- is there anything I can do to circumvent it (The device can output HTTP, UDP unicast / multicast, RTSP, or RTMP )

http://stackoverflow.com/questions/21232206/raw-h-264-stream-output-by-mediacodec-not-playble

http://stackoverflow.com/questions/13307086/decoding-raw-h264-stream-in-android

**Comment by Fleker** [comment]
I'm using ExoPlayer for playback, and I was pretty sure it supports this
codec.

**Comment by kartajan** [comment]
OK, since I still cannot get it to play in the app, this is the only way I could get this stream to playback on the NP. I am hoping this will provide enough input to figure out what I need to do to make it function. (Note that the regular android VLC app/ PC VLC play the stream fine by direct entry of the link "http://192.168.0.150:80/hdmi" )

put m3u8 file on PC
install IPTV plugin to Emby
setup link in IPTV plugin

Go to NP
browse "network" in VLC (DLNA)
open link in "emby", "video bookmarks", sharename

This is now playing, some A/V offset due to emby transcoding
[Emby Log.txt](https://github.com/Fleker/CumulusTV/files/140935/Emby.Log.txt)

[tfc.m3u8.txt](https://github.com/Fleker/CumulusTV/files/140936/tfc.m3u8.txt)
(this site doesn't support uploading the m3u8, so I just appended a .txt for upload)

**Comment by Fleker** [comment]
Hmm that's pretty odd. It is likely some unusual transcoding that isn't
supported by the media player I'm using:
https://github.com/google/ExoPlayer/

**Comment by kartajan** [comment]
do you know where I can find information on what codecs/ formats/ etc. are properly supported with enough detail to attempt setting my encoder's output to something that works?

**Comment by Fleker** [comment]
There's some supported formats mentioned on this page:
https://google.github.io/ExoPlayer/guide.html but I haven't been able to
find a specific list of supported codecs.

**Comment by kartajan** [comment]
that has links to here:
https://developer.android.com/guide/appendix/media-formats.html

which I reconfigured my stream per table #2 (H.264 Baseline, HD 720p), but nothing changed; still not playing the stream...

**Comment by kartajan** [comment]
related question.. in the "readme" you put out the JSON Format like so:
"url":"stream.m3u8", //Channel stream or website url

Does the app assume that the files are in Google Drive when not fully specified?
I am thinking to put a .m3u file there formatted as such:
#EXTM3U

#EXTINF:-1,TFC 
http://192.168.0.150:80/hdmi

**Comment by kartajan** [comment]
!!! I think I know why it doesn't work, but I need to know what I need to do in order to fix it.
I think the output of my HW encoder doesn't have a container. So what is the (best) way to fix that? My preference would be to have this happen on the Android device I use to view the content, but I am open to suggestions.....

**Comment by Fleker** [comment]
Sorry, I'm not entirely sure how to fix this issue.

**Comment by kartajan** [comment]
would it be possible to add an option to open the stream with VLC if installed?
I actually went and downloaded Android Studio in the hopes that it would hold my hand enough to make something work, but I got lost with a quickness.. Maybe a vlc/ channelsurfer app??

**Comment by Fleker** [comment]
VLC doesn't have the ability to embed their player in the app. As live
channels integration is a key part of Cumulus TV, this wouldn't create a
significant benefit to most users.
