### ISSUE TITLE
Sony Bravia Android issues specifically

### ISSUE THREAD

**Issue by alanmcramer** [Fleker/CumulusTV#103]
1.5.1 works great with making the channels show up in the Streaming Channels app now. But, upon viewing each channel, I get the famous "this channel will be available soon" screen and then black screen with nothing. Doesn't behave this way with the channelsurfer sample so wondering if it has anything to do with the showing of a title card.  Maybe Sony's app can't handle multiple things happening per channel.  Any way I can check a log of what is happening behind the scenes? The streams are working directly in the Cumulus TV app.

**Comment by Fleker** [comment]
The logs may not be clear enough to find an issue, but you could definitely
try.

I'm thinking that there may be an issue with the title card not going away.
It isn't happening for me though which is odd.

**Comment by alanmcramer** [comment]
Any way to disable the title card altogether?  Would be great if it was a switchable option in settings, or even if it detected what type of TV.  Open Live Channels link within Cumulus TV is still broken also.

**Comment by Fleker** [comment]
Do you know the package name for Sony's live channels app? If so, I can add
it to the button.

The title card will remain because it's just there for buffering. If that
didn't exist it'd be a black screen.

**Comment by alanmcramer** [comment]
com.sony.dtv.tvplayer

SonyTvPlayer.apk

**Comment by Fleker** [comment]
Thanks.
My guess is something related to the tuning timeout bug. It should be fixed in ChannelSurfer 0.2.8, so it should be moving over here soon.

**Comment by Fleker** [comment]
Sony TVs should work now.

**Comment by alanmcramer** [comment]
@Fleker unfortunately latest version updated from the play store has broke support for Sony. Streaming Channels app doesn't work at all along with trying to view channels within the actual app. The behavior in app is you get a gray screen followed by it returning to the channels page.

**Comment by josuearisty** [comment]
@Fleker, with this update, now it is completly broken for me. Every time I change channels I got an error message.

Im stuck in version 1.4.6 because this is the version that is at least working for me. With some issues but its working.
