### ISSUE TITLE
Build a ChromeOS version

### ISSUE THREAD

**Issue by alanmcramer** [Fleker/CumulusTV#104]
Build a version of the app that will work via ARC https://developer.chrome.com/apps/getstarted_arc

Even if it was just an editor with no video viewing capability to easily edit the json file via google drive.

**Comment by Fleker** [comment]
This is going to be low priority as there's usually better ways of
streaming on a laptop or desktop. Additionally, ARC doesn't seem to support
Drive APIs right now.

**Comment by bgiesing** [comment]
@Fleker Google might get around to it before you do http://www.omgchrome.com/google-play-store-coming-chromebooks/

All the apps in the Play Store on Chromebooks

**Comment by Fleker** [comment]
That's good because right now it wouldn't actually work on Chrome OS

**Comment by Fleker** [comment]
Okay full Android is coming to ChromeOS, not sure about non-COS laptops. Am going to close this issue because I won't need to do anything and have no plans to modify the system.
