### ISSUE TITLE
Editing via CumulusTV mobile interface seems to not update

### ISSUE THREAD

**Issue by alanmcramer** [Fleker/CumulusTV#105]
1. Open CumulusTV on mobile device
2. Ensure cloud file is selected
3. Select View Streams
4. Select a video in the list
5. Change attributes within Edit Channel box
6. Select Update
7. ???
8. No Profit.

Seems to revert back to the original information.

**Comment by alanmcramer** [comment]
Creating a New Channel seems to be broken as well.

**Comment by Fleker** [comment]
Am investigating

**Comment by josuearisty** [comment]
Its working for me in lastest version. Everything seems to be fine, except for some new visual issues. Will report later.

**Comment by alanmcramer** [comment]
Tried it again, and it appears to be working now.  I am now running 1.5.1 on the mobile device, so it may have been an issue with an older version.
