### ISSUE TITLE
Cumulus TV is listed as "Not Set Up" after loading channels

### ISSUE THREAD

**Issue by MateCurkovic** [Fleker/CumulusTV#107]
After that I went to  Live Channels app, then "Channel Setup" >> "Channel Sources", Cumulus TV is listed as "Not Set Up"

I'm on Nvidia Shield Tv 6.0 (marshmallow) 

I like this app, hope I can use it again.

**Comment by Fleker** [comment]
Try using the latest version, currently in beta, 1.5.1

**Comment by Fleker** [comment]
Fixed
