### ISSUE TITLE
Adaptive streaming support

### ISSUE THREAD

**Issue by albertogasparin** [Fleker/CumulusTV#109]
I was wondering: does Cumulus support adaptive streaming playlists? 
I have a TV stream that has a root index.m3u8 that contains the following code:

```
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=122032,CODECS="mp4a.40.2"
Stream(05)/index.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=425080,RESOLUTION=256x144
Stream(01)/index.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=686646,RESOLUTION=512x288
Stream(02)/index.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1185254,RESOLUTION=768x432
Stream(03)/index.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1798298,RESOLUTION=1024x576
Stream(04)/index.m3u8
```

Android starts playing the lowest stream (don't know if `05` or `01`) but it does not progressively switch to the higher res ones even if the bandwidth allows it. Meanwhile, setting the stream source directly to `04` for instance works. Is it a known limitation?

**Comment by Fleker** [comment]
In theory yes it should support adaptive streaming.

**Comment by albertogasparin** [comment]
Well, I've found another "public" stream that is better testable (same specs):

```
http://vevoplaylist-live.hls.adaptive.level3.net/vevo/ch1/appleman.m3u8
```

And I confirm the same issue: I can play it but Android keeps playing the lower quality stream. Is the adaptive stream handled by CumulusTV or is LiveChannels handling it?

**Comment by alanmcramer** [comment]
I've resorted to forcing Cumulus TV to use the highest m3u8 within the root index.m3u8 file, as I too find that is uses the first one in the list, which in a lot of cases is a lower quality version.

**Comment by albertogasparin** [comment]
Indeed, good enough approach. Is there a setting somewhere or it will be part of a next release?

**Comment by Fleker** [comment]
Playback is handled by ExoPlayer, so I'd have to figure out why it's
picking one stream over another.
