### ISSUE TITLE
NullPointerError in Program's InternalProviderData

### ISSUE THREAD

**Issue by fildy** [Fleker/CumulusTV#111]
hi, the latest release app is crashing with nvidia shield

**Comment by Fleker** [comment]
Thanks. I haven't seen any crashes on mine, but it's a known problem.

**Comment by CyberSardinha** [comment]
I have the same problem with the Nexus Player. It keeps crashing can't see anything at all

**Comment by Fleker** [comment]
Yeah I may have found the issue. Can you check the permissions for the app?
What's enabled and what's disabled?

**Comment by CyberSardinha** [comment]
Only storage shows. And it was disabled

**Comment by Fleker** [comment]
Can you enable it and check again?

**Comment by CyberSardinha** [comment]
(just repeating)

I just tried to enable it, erase all data and started again.

It allowed me to add one of the example channels on the app, but once I go to google live channels app and add cumulus as the source it crashes and from there on everytime I open the app crashes.

I'm quite free today to give you a hand on trying things and help you sort this out if you want.

**Comment by kgersen** [comment]
logcat when it crashes:

03-22 22:21:02.338: D/TvInputProvider(6468): com.felkertech.n.cumulustv/.SampleTvInput
03-22 22:21:02.345: D/TvInputProvider(6468): Program from channel content://android.media.tv/channel/273
03-22 22:21:02.345: D/TvInputProvider(6468): Program from chanel 273
03-22 22:21:02.345: D/AndroidRuntime(6468): Shutting down VM
03-22 22:21:02.731: E/AndroidRuntime(6468): FATAL EXCEPTION: main
03-22 22:21:02.731: E/AndroidRuntime(6468): Process: com.felkertech.n.cumulustv, PID: 6468
03-22 22:21:02.731: E/AndroidRuntime(6468): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.felkertech.channelsurfer.model.Program.getInternalProviderData()' on a null object reference
03-22 22:21:02.731: E/AndroidRuntime(6468): 	at com.felkertech.n.cumulustv.SampleTvInput.onTune(SampleTvInput.java:196)
03-22 22:21:02.731: E/AndroidRuntime(6468): 	at com.felkertech.channelsurfer.service.SimpleSessionImpl$TuningTask$1.handleMessage(SimpleSessionImpl.java:230)
03-22 22:21:02.731: E/AndroidRuntime(6468): 	at android.os.Handler.dispatchMessage(Handler.java:104)
03-22 22:21:02.731: E/AndroidRuntime(6468): 	at android.os.Looper.loop(Looper.java:148)
03-22 22:21:02.731: E/AndroidRuntime(6468): 	at android.app.ActivityThread.main(ActivityThread.java:5482)
03-22 22:21:02.731: E/AndroidRuntime(6468): 	at java.lang.reflect.Method.invoke(Native Method)
03-22 22:21:02.731: E/AndroidRuntime(6468): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
03-22 22:21:02.731: E/AndroidRuntime(6468): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)


device is a NVidia Shield with an adopted storage (64GB sd-card).

**Comment by Fleker** [comment]
That's a pretty simple to fix bug.

**Comment by Fleker** [comment]
Fixed in 1.5.2
