### ISSUE TITLE
m3u import problem

### ISSUE THREAD

**Issue by tam1m** [Fleker/CumulusTV#116]
Hi, I'm trying to import my m3u playlist but Cumulus does not recognize any channels. 
The format looks like this

`#EXTM3U`
`#EXTINF:0 tvg-logo="283d_Das_Erste_HD.png",Das Erste HD`
`#EXTVLCOPT:program=11100`
`rtsp://192.168.3.1:554/?freq=114&msys=dvbc&sr=6900000&specinv=0&mtype=256qam&tnr=0,114000,6900000,0,0,5,0,0,6020,6010,6000,11100,0,0,24,0,1051,41985,-1&pids=0,16,17,18,20,6000,6010,6030,6020,6021,6022`

rtsp not supported?

**Comment by Fleker** [comment]
RTSP isn't really supported

**Comment by JeanPrendnote** [comment]
same, my rtsp channels from my ISP for TV are like rtsp://mafreebox.freebox.fr/fbxtv_pub/stream?namespace=1&service=201&flavour=ld and not working ;'(
