### ISSUE TITLE
Ability to Group Channels

### ISSUE THREAD

**Issue by nextux** [Fleker/CumulusTV#120]
On the main page of Cumulus TV, I should be able to come up with my own Group Names and be able to group channels.  So currently you have "My Channels" and under that "Suggested Channels".  My suggestion is to have "All Channels", "Group 1", "Another Group"... "Suggested Channels".

Reason for this suggestion, I have a large list of IPTV channels, with some from Australia, and some from Indonesia.  It would be good to separate them, so if my partner wants to watch something from Indonesia, she doesn't have to scroll through all the Australian IPTV channels to get to the ones she watches.

**Comment by Fleker** [comment]
Interesting idea, but low priority for me.

**Comment by josuearisty** [comment]
When you have more than a hundred channels maybe its needed, you can do it by categorizite them, there is, movies, kids, science, etc.

The big problem for me its when I change channels, when I load my hundred channels list, if fails with most channels when Im tuning.

Is it there a way you could check this? The last build I was able to change all channels without problems was 1.4.7. but it took some seconds to change (more a minute sometimes) and sometimes it didnt change.

**Comment by Fleker** [comment]
Sorting by genres may not be too complex.

Yeah I can take a look at the import mechanics. Im working on a new import
system now.

**Comment by josuearisty** [comment]
The problem for is not importing channels, it comes when changing channels.

I sent you a video of it before.

When will you release next version, the lastest its having some serious issues!

**Comment by Fleker** [comment]
I'll be doing some debugging over the weekend. I have been getting a lot of
crash reports recently.

**Comment by bgiesing** [comment]
I wish Google themselves would allow this! I can't include Pluto in my Live Channels because it randomly gets placed in the middle of the other apps that I use more often meaning that sometimes I have to scroll through their almost 150+ channels to get to Cumulus (as it occasionally shows up as the package name and it uses lowercase after capital sorting)

**Comment by Fleker** [comment]
There are filters in a navigation drawer or voice search to tune to a
particular channel.

**Comment by bgiesing** [comment]
@Fleker I didn't think of Voice Search (but Voice Search is horrible with my lisp) and the nav filter is there but it's by genre or HD/SD quality and it would be cool of Google to add by provider so I can go to the sidebar and only show Cumulus channels or only Pluto ones

**Comment by FezVrasta** [comment]
May you please just support the groups like IPTV Pro does?

Example:

```
#EXTINF:-1 group-title="GROUP NAME HERE",CHANNEL_NAME_HERE
http://example.org/stream.ts
```

**Comment by Fleker** [comment]
It's low priority at the moment in terms of what I'm developing.

**Comment by FezVrasta** [comment]
I don't get it... All the IPTV services have hundred of channels, how we are supposed to navigate trough them without any kind of organization?

**Comment by Fleker** [comment]
I understand that it can be inconvenient. Although there are other issues I
also want to tackle and I only have a certain amount of time.

I'm willing to accept contributions from other individuals, although my own
contributions will be at a certain speed.

**Comment by Fleker** [comment]
I've made some headway in the most recent release. I'm not pulling the group name from imported m3u playlists yet.

**Comment by alanmcramer** [comment]
Will there be a group setting added to the json file?

**Comment by Fleker** [comment]
Right now I'm using the genres component

**Comment by alanmcramer** [comment]
After seeing how this works, it is an improvement over the previous setup of having all the channels in one line.

**Comment by FezVrasta** [comment]
@Fleker , I see the cumulus app shows the channels organized by group (gathered from the M3U plist) but in the Live TV app the groups aren't there. Are you working on it, is it a bug or what?

**Comment by Fleker** [comment]
The live TV app isn't mine. It groups based on certain genres. Not a bug.
No fix planned.

**Comment by FezVrasta** [comment]
I know it's not yours 🙂 but since it does support categories, I guess there must be a way to use them?

**Comment by Fleker** [comment]
They are being used if you use the system genres.

**Comment by FezVrasta** [comment]
do you have a link where I can find more info? I don't think I understand

**Comment by Fleker** [comment]
Docs will be added soon. Follow new issue for updates.
