### ISSUE TITLE
Confused on how to use m3u and multiple channels to import

### ISSUE THREAD

**Issue by Rochey** [Fleker/CumulusTV#122]
I pay for an iptv stream service with over 400 channels. The link that I use goes to an m3u file containing a list of all the channels like this:
# EXTM3U
# EXTINF:-1,OSN BBC 1

http://iptv.abciptv.com:80/live/yyy/xxx/192.ts
# EXTINF:-1,OSN BBC 2

http://iptv.abciptv.com:80/live/yyy/xxx/582.ts
# EXTINF:-1,OSN ITV 3

http://iptv.abciptv.com:80/live/yyy/xxx/440.ts

How do I get this imported into Cumulus TV so that I can then use the Android TV Live channels?
I've manually entered 1 channel using the "add channel" feature and it works perfectly, but I don't want to have do this for the other 400.
Any help would be much appreciated.

**Comment by Fleker** [comment]
There should be an option to open up the file with Cumulus TV and bulk
import them.

How are you opening the file?

**Comment by Rochey** [comment]
I've tried on 2 devices:
Android TV, I used ES explorer and tried to open the m3u but CumulusTV wasn't an option.
Android phone (side loaded), I used Google drive and FX explorer but neither or those gave me an option to open in CumulusTV.

I did try and rename the m3u to m3u8 and on the Android phone it gave me an option to open the file with CumulusTV but when it opened I had a channel created for each line on the m3u8 file. So it didn't really work. Not sure if that was the right thing to try.

Android phone is on N beta and the Android TV is M 6.0.1 (nvidia shield).

**Comment by josuearisty** [comment]
You should tap on the file, then opened as TEXT then you will see cumulusTV.

I hope this helps

**Comment by Rochey** [comment]
Thanks for the info, but could you be a bit more specific please?
Is this on the phone/android tv? using ES explorer or default app?

I just tried using FX explorer on my phone but Cumulus TV wasn't an option still. Also tried ES explorer on the Android TV but opening as text opened it in the ES explorer text editor.

**Comment by josuearisty** [comment]
I do it in the phone, I tap a m3u channel list, open as text, the you will see the option "create a cumulustv channel".

Nick Im really happy man! 😂😂😂

This is the first build that its working almost perfect for me. Wow

I can change channels without problems, I was able to load my whole list, more than a hundred channels and they all work fine.

I just had some issues trying to save they json file to drive, I dont know why it creates a file with 0kb.

Plus I had to set permissions by myself.

Are you planing to add more languages? Im planing to translate this to spanish, but if you will add more languages, I can help with translation.

Thanks man! I love this build.

**Comment by Rochey** [comment]
Think I've got it! 
I had to enable storage permission on my phone to allow the m3u import - before doing that I was getting "permission denied".

I've now got the channels imported (all 620 of them) and they work on the phone, sort of..... opening the channel sometimes shows a black screen but going to the edit channel option, the little preview of the channel works, very strange and I'm not that bothered about the phone as I want it to work on the Android TV.

Android TV is giving some pain though, I'll open another issue I think.
Thanks for the help in importing the m3u. To try and help others this is what I did:
Give Cumulus TV storage permission in Settings > Apps > Cumulus TV > permissions
In FX explorer > long press m3u file > open with > Open as > Plain Text "text/plain" > Create a Channel (this should import the m3u into Cumulus TV and show you a list of all the channels that are about to be imported).
Cheers

**Comment by josuearisty** [comment]
Exactly, hey Nick would you please take a look at the permissions issue?

Plus I have to say IM ABLE TO PAUSE channels! 😎

**Comment by Fleker** [comment]
Yes I'll take a look at permissions again. It's supposed to say something
when you start the app, in the tutorial, but I'll check again.

Your syncing issue is strange. It saves fine for me so I'll see what's
there.

And I would be happy to see more translations. Send me a pull request with
them and I'll integrate it.

**Comment by josuearisty** [comment]
For creating json the file I had to try some times, but worked.

Nick check this image:
https://drive.google.com/file/d/0B2vu-1nch9eYVmt0Y0ZFbDhpR00/view?usp=drivesdk

This black screen is what he is getting, it happens to me sometimes. I tried changing channels more than 2 hundred times maybe and I have get the this issue twice.

**Comment by bgiesing** [comment]
@Fleker I've had similar syncing issues. Sometimes Google disconnects and when you try to sync it again, it won't let you select your existing file and makes a new empty one that I have to open Drive on the computer and copy/paste my old file. If I haven't been deleting the duplicates, I would have 10+ files just after using the app for a few months.

**Comment by Fleker** [comment]
You should be able to import an existing file if there's a connection issue.

When the storage permission wasn't enabled and you tried to import, what
happened? Was there an issue?

The image above with the video player can happen if ExoPlayer has an issue
and it puts the stream in a webview.

**Comment by josuearisty** [comment]
@Fleker when the storage permission wasnt enabled I just got an error message, nothing happended.

**Comment by keds2300** [comment]
@Rochey any luck in getting this working on Android TV?

**Comment by Rochey** [comment]
@keds2300 I've got the channels on Android TV but they are a bit unreliable. I get a black screen most of the time but the same channel works using another app like "IPTV". The easiest way to get the channels onto Android TV was to use your phone/tablet to create the json file on google drive using the method I said above. Then on Android TV you can just import the json file. That process is quiet easy now I know how to do it.
Like I said though the channels and a black screen is the next issue I've got. There doesn't seem to be any pattern to the issue though. 1 minute the channel is black, change the channel and come back and then it works??? Then the next time I try to use it the channel is black again.
Good luck, YMMV

**Comment by owlsy1971** [comment]
hi ive got the same problem i can create one channel easily but when i try opening m3u txt file it shows blank no channels in cumulus.question what format does the txt file need to be just converted it to m3u list as above but will not recognise in cumulus app,using my phone to open any help would be appreciated apart from that would like to say thanks to the developer for and excellent app

**Comment by Oopas** [comment]
I'm having the same problem as Rochey :(
"Opening the channel sometimes shows a black screen but going to the edit channel option, the little preview of the channel works, very strange"

How can I solve that ?

**Comment by Fleker** [comment]
If you can look at the adb logs, that may give some clue. There's no reason
why that should happen.

What device do you have?

**Comment by princeolivier78** [comment]
hi guys thanks nick for your hard work,
i have managed to get it working on the android tv after hours of trying till i figure out the easiest way was to install the plugin from your phone to the android tv so instead of using your phone you use the android tv with es explorer then open as text then create channel then you good to go i did experience some crashing but after i restarted the tv it working fine some buffering but ok so far and backed up the json file just incase :)

**Comment by princeolivier78** [comment]
https://drive.google.com/file/d/0B_EQ3iMIe5ydeW81TWRpNEpMYUU/view?usp=sharing

**Comment by Fleker** [comment]
Okay I'll be developing a useful guide soon and add more documentation to
the website.

**Comment by princeolivier78** [comment]
Thanks nick thanks again for this great app 👍👍👍
