### ISSUE TITLE
Philips PUS8601

### ISSUE THREAD

**Issue by imbalancedzero** [Fleker/CumulusTV#124]
Hello World of Cumulus TV

I've installed the app on my Philips PUS8601 and so far so good. Culumus TV appears in the Leanback Launcher to configure and appears under Sources when I scroll down to the bottom.

The issues:

Firstly, these issues could be down to Philips, Android or Culumus TV, but I guess this is a good place to start.

My main source is Satellite. When I set up Culumus TV from sources, it managed to mess up my satellite channel list. After a hard reboot, all the satellite channels were gone and I had to reinstall them through the manufacturer process. Edit...I've realised that if I disable the channels in Live Channels the native TV app cannot see them either. Once enabled they are there again.

After installation, the channels appear in Live Channels via Culumus TV but I can only hear audio on the Satellite channels, the screen is blank.

Once I chosen a satellite channel none of the HLS channels work. The screen is blank and there is no audio. If I go back to a satellite channel then I can hear only the audio of the channel. Edit..My workaround is to select a HLS channel and choose Sources on my remote and then choose back. The HLS channels will work again.

When I try and open Live Channels from the Culumus TV app itself, it pops up and asks is Live Channels installed?

**Comment by Fleker** [comment]
Philips TVs are doing something unusual and I don't exactly know what I
should fix.

**Comment by kyvaith** [comment]
Confirm, I'm facing same issue with cable TV on Philips 7600. It's propably related with Google Live Channels list auto managment. What version of GLC you are using? Does it comes preloaded on your TV or you need to sideload it?

**Comment by Fleker** [comment]
This should be fixed soon.
