### ISSUE TITLE
Using CumulusTV with HDHomerun+Wallop

### ISSUE THREAD

**Issue by jtd5048** [Fleker/CumulusTV#127]
Great work on this so far. It's oh-so-close to my dream setup. I have a Nexus Player and would like to transport transcoded streams from my HDHomeRun Prime over WAN. I'm using a project called Wallop (maddox/wallop on github) to tune the HDHR, start transcode, and create an HLS URL.

The problem comes from the fact Wallop uses a three step process to use a tuner:

1) POST http://server:port/channels/channel#/tune
This tunes the HDHR and begins the transcoding process

2) GET http://server:port/channels/channel#/status
This checks status of transcode. It returns a JSON object describing the transcode session. "ready" needs to return "true" and then....

3) GET http://server:port/channels/channel#.m3u8
An m3u8 URL is finally created and using this URL streams the transcode session via HLS

The problem is that I can't (as far as I can think) perform the first two steps inside of Android TV. Obviously, opening a channel that has not been tuned does nothing. I can manually start a transcoding session of a channel in Wallop's webUI, and THEN hit that URL in Live Channels via CumulusTV, and this works beautifully. If the Channel has been selected in Live Channels, I have to change channel, then change back to view the stream, which is not ideal.

Do you have any idea how I can tackle the POST and then check STATUS of Wallop in order to use all my channels? Would there be a way to shoot off the POST and then GET status in CumulusTV? Would I have to go the route of creating my own plugin? I'm really hoping I can get this seamless via CumulusTV/Live Channels

**Comment by Fleker** [comment]
Hmm right now there's no way to get a callback without a custom plugin.

Maybe if you opened a web url that could connect to and playback the media
from that webpage hosted locally.
