### ISSUE TITLE
Custom programming

### ISSUE THREAD

**Issue by Fleker** [Fleker/CumulusTV#13]
Allow users to specify custom `XMLtv` files so you get accurate programming information.

**Comment by Fleker** [comment]
I'm hoping to have something ready by the end of the month.

**Comment by bgiesing** [comment]
Any way to use a ics/Google Calendar? TWiT.tv is a great source and they have an auto-updating Google Calendar with the latest info. https://www.google.com/calendar/ical/mg877fp19824mj30g497frm74o%40group.calendar.google.com/public/basic.ics

**Comment by Fleker** [comment]
I don't think I'll go the calendar route. For live streams that run 24/7
most seem to use an XML format.

**Comment by bgiesing** [comment]
@Fleker Google Cal also has a XML: https://www.google.com/calendar/feeds/mg877fp19824mj30g497frm74o%40group.calendar.google.com/public/basic

**Comment by Fleker** [comment]
True, although it's in a different format/spec. So calendar support could appear down the line but it'll be farther down on my priority list.

**Comment by bgiesing** [comment]
I looked online for a way to convert to XMLTV and all the links are the opposite, XMLTV to ICS. LOL I think more people want ICS online.

**Comment by Fleker** [comment]
If I'm writing a custom parser for one, I think xmltv overall is more popular. I don't know if there's an ics library I can import.

**Comment by bgiesing** [comment]
@Fleker This maybe? https://github.com/ical4j/ical4j

**Comment by Fleker** [comment]
I'll look at it. If I can find a way to convert XMLTV it'll be easy to
handle both.

**Comment by Fleker** [comment]
I'm closing this issue because I have successfully created an XMLTV parser within the app. With regards to its integration in current channels, please refer to #36 

As for using iCal, refer to #37.
