### ISSUE TITLE
Importing channels from a web server

### ISSUE THREAD

**Issue by 9point6** [Fleker/CumulusTV#133]
I've written a tool which generates my channel json file, at the moment it's possible to dump a copy into my google drive and then sync it that way, but it'd be great if I could specify a url for Cumulus to use to cut google drive out of the equation.

This would allow me to ensure the list of channels is up-to-date when Cumulus syncs

**Comment by josuearisty** [comment]
Yes, we need some way to upload the json file without using gdrive, my brother's nexus player cant select json file saved in drive, dont know whats really happening.

**Comment by Fleker** [comment]
So do you want an option to point to any URL instead of a Drive file, or
have some mechanism where Drive continues to work, but it also calls
another URL to gain additional channels?

**Comment by josuearisty** [comment]
It would be great but I really wish to have some way to load the json file locally. And a way to save it loacally, for example we can add channels to cumulus app, then save it to some folder inside storage.

What do you think?

Thanks

**Comment by Fleker** [comment]
I have tried to stay away from that. If enough users want that, then sure,
but I don't think it's a great user experience to do file management on
your TV.

**Comment by josuearisty** [comment]
Well, I understand what you mean, you could make it optional in settings or something like that, so that not everybody knows about it.

**Comment by Fleker** [comment]
If enough people vote for this issue then I'll add it in. But I want to
start focusing on stability too and start testing critical parts of the
app. I don't want to create a large test suite of unused features.

**Comment by 9point6** [comment]
Yeah, I wouldn't mind either situation really. If it's easier to have an either/or with regards to google drive or hitting an endpoint, that'd be fine!

**Comment by Fleker** [comment]
So this is actually one area that the plugin model could work. The flow would be like this:

* User wants to add a channel
    * They select from "Add a Channel" or "From Url"
* The `From Url` lets users specify a Url
* The plugin downloads data from that URL, parses if necessary, and caches channels
    * If Google Drive is enabled, then this is synced. Otherwise, it stays local.
* Periodically, when the syncing occurs, the plugin is called again and caches the channels again.

What do you think?

@josuearisty could you create a new issue for loading / saving data to a local system file? That way users can vote there and simplify each issue.

**Comment by josuearisty** [comment]
Hi Nick, when you say "add a channel from url", does ot means add the json file or what? Or just add the m3u8?

It would be great to have an option to add a whole json list from a url or locally (if you can).

Or better yet, what about select a m3u file (url or local) and then it will be converted to a json list and loaded inmediately to cumulus?

Thanks

**Comment by 9point6** [comment]
@Fleker That sounds perfect for my use case! Also as a nice-to-have, it'd be great if the syncing interval was settable per-plugin too, As I know my endpoint would only need to be hit once a day.

Is there another issue with details about this plugin system or is it still being fleshed out? You've got me thinking about a few ideas now, haha

**Comment by Fleker** [comment]
Yes I had started adding support for loading any type of data from a URL or locally, so it could be an m3u playlist, JSON file, or XMLTV file that users are able to input.

The plugin model already exists, and an early model is described in [the wiki](https://github.com/Fleker/CumulusTV/wiki/Create-a-3rd-Party-Plugin). However, I'm planning on improving it and publishing it on [the official webpage](http://cumulustv.herokuapp.com/docs/Plugin_API/Introduction.html).

**Comment by alanmcramer** [comment]
I would love to point cumulus TV to a URL and have it pull the json every time I start the app.

**Comment by Fleker** [comment]
Refer this to #153 and integrate into next build.
