### ISSUE TITLE
importing channels 

### ISSUE THREAD

**Issue by owlsy1971** [Fleker/CumulusTV#137]
hi my issue is importing channels i can create one at a time easily but need to import several hundred i have an account with channels converted them to m3u but when i import txt file cumulus says no channels found is it an issue with my m3u txt file or an import issue with cumulus and help would be appreciated.

**Comment by Fleker** [comment]
It may be a problem with the m3u parser. If you can provide the file,
either here or by emailing me, I can take a look at the logs.

Maybe it's a permission issue. Does the app have access to storage?

**Comment by owlsy1971** [comment]
Hi thanks for the reply I've sorted it was the way the converter put format into m3u file, do you know any good online m3u converters online don't want to write out hundreds of channels

**Comment by Fleker** [comment]
If you can provide a sample of how this converter creates files I may be
able to get around that.

I don't know of any good converters in particular.
