### ISSUE TITLE
EPG

### ISSUE THREAD

**Issue by josuearisty** [Fleker/CumulusTV#140]
Hi nick!

The app has some minor issues, but for me is being perfect until now. But the app is missing EPG support which is something really useful most times.

Is there any plan to make it possible soon?

Thanks

**Comment by Fleker** [comment]
Thanks. It is definitely on the roadmap. It'll be available soon.

**Comment by josuearisty** [comment]
Thanks!

Do you accept donations? Im not working right now, but I hope I get something in the coming days. I would like to donate to your amazing app!

**Comment by Fleker** [comment]
Thanks. I currently don't have a means to accept donations, but it's something I'm looking into.

**Comment by Fleker** [comment]
@josuearisty I wouldn't want to have a pure donation system. Do you think it would be reasonable to have an IAP that would give one early access to features?

**Comment by josuearisty** [comment]
@nick I shouldnt be speaking about this, people will complain on me, cause Im telling you to make an app with IAPs. Hehehe

It would be great in my opinion, you can get something for your amazing job.

Get some early or specials features with IAP would be great.

And please, dont make it expensive! Heheheh

**Comment by bgiesing** [comment]
@Fleker I don't know if it's a libary or can be used on TV but you should look at how the Stitch and Share app does it. They allow you to choose what you think the dev supports from a list of options which will give that amount of money though IAP. There's is attached to a pro version that removes a watermark but you could do it for just donations or early access like you said above.
