### ISSUE TITLE
Adding icons 

### ISSUE THREAD

**Issue by owlsy1971** [Fleker/CumulusTV#141]
Hi got my channels all working I must say it's a great app, problem is I would like to add icons but when I try ro do this in app on phone I can't paste in to existing channel lists, I don't want to type each url be nice to just copy link then paste into app channel is their another way to do it cheers

**Comment by Fleker** [comment]
The icon field is just an `EditText` field. Why can you not edit the channel data and then update?

**Comment by owlsy1971** [comment]
I can but means inputing long urls lol you can't paste one in

**Comment by Fleker** [comment]
Why can't you paste long URLs?

**Comment by owlsy1971** [comment]
When I tried it, the paste function never came up on my phone like it was disabled

**Comment by Fleker** [comment]
That's really odd. I was able to copy and paste without issue, so it's not an app bug.

**Comment by josuearisty** [comment]
@nick what app do you use in your phone?

Im using remote Android TV from innovation lab, but Im not able to copy from nexus player, I just can copy to.

**Comment by Fleker** [comment]
@josuearisty I have been referring to the Cumulus TV mobile app. Clipboard functionality would have to be an issue with the remote app.
