### ISSUE TITLE
Create Plugin Model

### ISSUE THREAD

**Issue by Fleker** [Fleker/CumulusTV#15]
It's not very straightforward to get a Twitch stream: http://www.johannesbader.ch/2014/01/find-video-url-of-twitch-tv-live-streams-or-past-broadcasts/

The process is complex enough that it would require a little bit of effort for a special case, but not enough that it's impossible. This creates the question of what direction CumulusTV should go in. Should I spend my time working in special cases?

I've decided to go to the plugin model, like Muzei or Tasker. This would allow me to keep a relatively vanilla interface, but allow specific users to add plugins to get specific streams.

Though I haven't decided on everything yet, here's the basic gist for this issue:
* Allow 3rd party apps to be called from within the channel creation
* Allow 3rd party apps to send a `JSONChannel` back for writing

**Comment by amgmetallica** [comment]
If you could find a way to automate the process of finding/check the video url based on the channel without the user having a lot of input so it's hassle free then it'd be good

**Comment by Fleker** [comment]
I'm probably going add an attribute to each plugin generated channel which
I'll call on the TV input service. That plugin will have to do the work and
return the stream URL to the service.

**Comment by Fleker** [comment]
I need to clean up some code, remove the "Ignore" option, and auto select if one exists.
