### ISSUE TITLE
"Open Stream" button in each channel should open that channel in Live Channels

### ISSUE THREAD

**Issue by Fleker** [Fleker/CumulusTV#152]

**Comment by Aulavik** [comment]
Would  you mind delete "add suggested channels "button, and setup default TV channels to "Open Stream"? I don't think "add suggested channels‘  is good idea . Thank

**Comment by Fleker** [comment]
So the channels that are provided should be automatically added? The
purpose of "suggestions" was so you could choose to add certain ones,
opting in instead of having to opt-out.
