### ISSUE TITLE
Add a JSONListing object so users can quickly include other URLs

### ISSUE THREAD

**Issue by Fleker** [Fleker/CumulusTV#153]
The importing model takes a snapshot of a particular file at that time, meaning the content owner is not able to update the files later. This can be inconvenient when trying to update a bunch of links later, especially when having to delete the current channels.

To make this easier, what if the user added a `JSONListing` which would just be a link to the actual URL. When passing over this listing, the app will pull from that URL again, keeping content fresh.

Example:

```
channels: [
    {
        title: "Random Channel", // Example of a current channel
        ...
    }, {
        link: "http://example.com/streams.m3u" // Example of a listing
    }
]
```

This is low priority right now

**Comment by josuearisty** [comment]
This should be high priority I think. It would be great to make it easier to modify channels.

**Comment by Fleker** [comment]
There are some other things I want to focus on first, like the EPG and more
stability. This is nice to have but not necessary.

**Comment by josuearisty** [comment]
Well yes, EPG and stability are much more important now.

But instead if being low priority, should be ser to medium at least, I dont change url channels al the time, but I do it sometimes and I have to erase the whole list then add the new and sometimes it doesnt update inmediately.

Thanks

**Comment by Fleker** [comment]
For this to work, I need to create another class and add code in the json
parser to separate channels and links, handle each case differently, and
create more tests.

If I went the plugin route, it could have similar results by injecting
channels into the json file when it's called, although it is harder to edit
in the future and creates larger files.

When people share their channels this can be a problem as theres no easy
import & merge json files. It should be easy to share various lists.

So the plugin would be medium priority, and doing it this better way is
lower due to the amount of work and ability to do workarounds.
