### ISSUE TITLE
Add a test suite for M3u

### ISSUE THREAD

**Issue by Fleker** [Fleker/CumulusTV#163]
There are a lot of different m3u formatted files. Lets collect some and write tests using them to improve our parser.

Since we'll be adding export support in #41, we can test our own output.

**Comment by josuearisty** [comment]
This is how my lists usually looks like:


#EXTM3U
#EXTINF:-1 tvg-name="Canal 2 HD" tvg-logo="http://y.cdn.entutele.com/media/channels/big/canal-2-hd.gif",Canal 2 HD
https://totalgo.total.com.mx:444/TPMHLSWeb/M3U8LiveFile?a=&f=.m3u8

#EXTINF:-1 tvg-name="Foro TV HD" tvg-logo="http://y.cdn.entutele.com/media/channels/big/foro-tv-hd.gif",Foro TV HD
https://totalgo.total.com.mx:444/TPMHLSWeb/M3U8LiveFile?a=&f=.m3u8

**Comment by Fleker** [comment]
Thanks. I'll be adding this as an example in the test suite.
