### ISSUE TITLE
Add a section to insert EPG Url

### ISSUE THREAD

**Issue by Fleker** [Fleker/CumulusTV#168]
The `MainPicker` needs a text field for the EPG url. Right now the feature is available, but hidden.

**Comment by josuearisty** [comment]
Great! Thank you very much for this!

How will it work?

**Comment by Fleker** [comment]
Similar to a logo URL or a stream URL, users will be able to add a URL pointing to an `XMLTV` file. When the system resyncs, it will download that program data and populate the EPG with those programs, repeating if necessary, until it fills up the guide.

**Comment by josuearisty** [comment]
Excellent! I will be waiting for it!

**Comment by josuearisty** [comment]
Hi nick, I updated now to 1.6.0, I would like to know where will I add epg url in the json file?

Any example for this?

Thanks

**Comment by Fleker** [comment]
@josuearisty you can use the `epgUrl` attribute and set it to a url

    {
            "number": "1337", 
            "name": "Aquarium",
            "url":"stream.m3u8",
            "epgUrl":"http://example.com/programs.xml"
        }
