### ISSUE TITLE
EPG hints or tips

### ISSUE THREAD

**Issue by liquid64** [Fleker/CumulusTV#176]
I'm wanting to start experimenting with the EPG stuff.  Was curious is you have any tips on getting XMLTV urls.  I have a subscription to schedulesdirect, but it's not very clear how to get the raw XML.  Are there any other 3rd party sites you were using to test with?

**Comment by Fleker** [comment]
I was not testing with any 3p sites, just using a custom local file to test
functionality. I'm not sure how to obtain the raw XML files for a specific
site.

**Comment by liquid64** [comment]
Thanks for the reply.  So, I have figured out how to use tv_grab_na_dd ( http://manpages.ubuntu.com/manpages/wily/man1/tv_grab_na_dd.1p.html ) to pull data from schedules direct.  Although I have the epgUrl attribute set to the XML, I'm not seeing anything under Live Channels yet.  I cleared data from cumulus, just to make sure I'm working with a fresh grab from my Drive.  Will keep playing with it, and if I get anywhere, I'll post back.

**Comment by liquid64** [comment]
Here's a copy of my XML docs https://drive.google.com/open?id=0B42Khmey83mzQVBXaE5HdzMtUjA

**Comment by Fleker** [comment]
Yes let me know what you see. If you see a problem, you can use the report
playback issue in the App Link. It will send some debug information that I
can use to test.

**Comment by bgiesing** [comment]
I have been looking all over and can't find any calendar to XMLTV parsers, only the reverse. I want to add TWiT's schedule (which basically never changes) found here http://wiki.twit.tv/wiki/Schedule but I can't figure it out as I know nothing about XMLTV.

**Comment by Fleker** [comment]
TWiT uses iCal instead of XMLTV. It's another file format I'll have to build a parser for. That's currently open as issue #37
