### ISSUE TITLE
1.6.2 Broken on Sony Android TVs

### ISSUE THREAD

**Issue by alanmcramer** [Fleker/CumulusTV#177]
Unable to use Google Drive features.  Multiple Issues.
1. Unable to create new JSON
   a) Select Connect to Google Drive upon new install
   b) Select your account
   c) Select OK to creating a syncable file
   d) Use onscreen keyboard to select "Next"
   e) Take note that "Cancel" option is selected for some reason
   f) Onscreen keyboard is still visible, select Finished.
   g) Screen goes away, no JSON created (assuming it selects this Cancel option)

Workaround 1: Press back on remote to remove onscreen keyboard then select right, then Save on Google Drive screen
1. Unable to Import from Google Drive
   a) Select Import from Google Drive
   b) Take note that My Drive loads, but unable to select any of the files in the middle
   c) Using arrows on remote, you will move between Magnifying Glass and Cancel buttons, or any other icon at the top, but not able to select a folder or file

Workaround 2 (sometimes works): Select magnifying glass, type in "cu" then select search on onscreen keyboard.  Use cancel button on remote. Press down, and you'll note that a file will appear to be select, scroll until you find file, then select.  Then select "Write Cloud Data to Local" then take note of "Couldn't find any channels.  Uh Oh." even if the JSON you select is full of channels.

**Comment by alanmcramer** [comment]
Working fine using the 1.5 series

**Comment by Fleker** [comment]
Yes Google drive has a bad UI for TV. It's an issue I'm planning on
tackling soon.

**Comment by alanmcramer** [comment]
Another bug is when using the Sony equivalent of the Live Channels app (Streaming Channels), it displays "The loading screen can't seem to open, but the channel is loading." but this displays whilst showing the default loading screen of Cumulus TV (the one where the channel logo is in the middle of the screen.

**Comment by Fleker** [comment]
That's a message that will pop up in very rare circumstances without a good reason. It'll be something I look over and remove if possible.

**Comment by alanmcramer** [comment]
I've noticed that cumulus TV is crashing often on both my Sony and my Nexus Player. Assuming these are coming through to your crash log @Fleker

**Comment by Fleker** [comment]
Yes I'm getting them
