### ISSUE TITLE
Remove VEVO streams

### ISSUE THREAD

**Issue by Fleker** [Fleker/CumulusTV#180]
Some users have commented on the low quality of some of my streams. For HD televisions, having high quality content is important. I wonder if there's an easy way to get an HD stream.

**Comment by bgiesing** [comment]
@Fleker VEVO discontinued VEVO TV so the streams shouldn't work anymore now https://www.google.com/amp/variety.com/2016/digital/news/vevo-website-relaunch-1201762833/amp/

**Comment by Fleker** [comment]
Oh well. I'll remove these streams then.
