### ISSUE TITLE
Crash every time I click to add a channel

### ISSUE THREAD

**Issue by FezVrasta** [Fleker/CumulusTV#186]
When I open the app on my HTC One M8 and I click on ADD NEW CHANNEl the app crashes.

I sent a crash log using the built-in feature of Android, is it enough?

**Comment by Fleker** [comment]
I do get crash reports through an internal service, so I should have
received it and should be able to develop a fix.

**Comment by FezVrasta** [comment]
Thank you! Let me know if you need any help with the testing.

May you provide an apk of the latest release to test it out? The Play Store version is still 1.6.4

**Comment by Fleker** [comment]
You can look at the GitHub releases section for more up to date version.

**Comment by FezVrasta** [comment]
I can't find the APK tho :(

**Comment by Fleker** [comment]
Currently the most up to date version is 1.6.4. I needed a new release
primarily for Jitpack to work.

**Comment by FezVrasta** [comment]
I see, thanks. Please let me know if I can help you in any way. (I'd also like to contribute to the project but I can work on Android only with React Native 😓 )

**Comment by Fleker** [comment]
You don't have any other Android experience aside from React?

**Comment by FezVrasta** [comment]
No sorry, I'm mainly a JS developer, for fun I started looking into React Native because I already use React at my workplace.

**Comment by FezVrasta** [comment]
Thanks! Any ETA for the release?

**Comment by Fleker** [comment]
It's available now

**Comment by FezVrasta** [comment]
Thanks, works perfectly now.
