### ISSUE TITLE
Include some sort of ability to donate

### ISSUE THREAD

**Issue by nextux** [Fleker/CumulusTV#190]
Personally, I think you do an awesome job @Fleker and whilst I would love to contribute more to this project, my coding skills are nearly non-existent (only can do HTML/CSS/JS/PHP).  I think there are a lot of people who would love the ability to buy you a beer (or just to donate to the project in general).  An option within the Settings screen or About screen to be able to donate would be a cool way for people to show their appreciation.

Thanks again.

**Comment by Fleker** [comment]
This will be implemented in an upcoming update

**Comment by nicco** [comment]
+1, it's an incredible job you are doing @Fleker !

**Comment by nicco** [comment]
and really that could just be to give us your paypal email
