### ISSUE TITLE
Switch to using the TIF companion library

### ISSUE THREAD

**Issue by Fleker** [Fleker/CumulusTV#196]
See: http://android-developers.blogspot.com/2016/11/adding-tv-channels-to-your-app-with-the-tif-companion-library.html

**Comment by alanmcramer** [comment]
Is this the successor to the ChannelSurfer library?

**Comment by Fleker** [comment]
Yes, ChannelSurfer is being deprecated

**Comment by Fleker** [comment]
Work on updating library and ExoPlayer now

**Comment by nextux** [comment]
With TIF supporting both channel icon as well as channel banner, will we see both implemented via cumulus? I'd love to be able to use a white channel icon for the channel and coloured banner within cumulus tv itself.

Examples of both at http://tv.cramer.id.au/indonesia for example.

**Comment by Fleker** [comment]
TIF does not support a channel icon & banner, just a single image for the channel. See [the Channel class](https://github.com/googlesamples/androidtv-sample-inputs/blob/master/library/src/main/java/com/google/android/media/tv/companionlibrary/model/Channel.java) for all possible attributes.

A [program](https://github.com/googlesamples/androidtv-sample-inputs/blob/master/library/src/main/java/com/google/android/media/tv/companionlibrary/model/Program.java) can contain a poster and thumbnail, although I don't know what is done with the poster art. The thumbnail is displayed in the guide.

With regards to the original issue, this is now working and will be in the upcoming beta.
