### ISSUE TITLE
Channel list and editing

### ISSUE THREAD

**Issue by HerrSchultze** [Fleker/CumulusTV#2]
Hallo Nick Felker,

I tried your Cumulus app.  Thanks for the work. It looks to me like the app I'am waiting for, since using the NP.
Your preinstalled channels work. A bit slow, but okay.

My hardware: Nexus player, Android TV 5.1.1. For remote control "Samsung S5", "Nexus 7 (2012)" (both with Lollipop and ).

I have some problems using the app.
1) To add an own channel gives me a hard time. I tried to use the official nexus remote app, at Mobile and Tablet. After inserting the channel name and the stream-adress, the result at the TV-screen is different of the Tablet or Mobile screen. 

2) I have problems to edit a stream. After "pressing" the update button, no change is saved. It is not possible to edit the entry.

Suggestions:
1) What do you think about an "Export" (and Import-) function for the channel list? So the user could edit/handle the list more easy. Guess, to use the small nexus-player-remote-control to insert each channel by hand is a crime ;) 
2) It would be great to have an option to (easy) use/load "Channel-Logos" from a local folder. 
3) What is your idea regarding the epg? 

Thank you in advance

Matthias

**Comment by Fleker** [comment]
Stream speed is dependent on those hosts. They stream videos from a few sources, and I don't have control over them.


Bug 1. I'll take a look at adding channels from the remote and figure out what's going on.

Bug 2. I'll look at how I'm doing updates, maybe I'm checking against an attribute to make sure it's the same stream but you're changing that attribute.

Sugg 1. My plan is to integrate Google Drive you can quickly view and edit channels anywhere.

Sugg 2. Right now it would be difficult to use local photos. As I plan to use a cloud storage option, I might also upload local logos to Google drive.

Sugg3. I haven't looked at how other organizations do this, whether there's a standard I could use or some common ways I can parse data. I don't want to create a proprietary way that requires manual work if I can help it.

**Comment by HerrSchultze** [comment]
Thanks for reply.

1) Google drive integration sounds good.

2) Regarding EPG.:
The common concept seems to be XMLTV. May have a look at the popular "IPTV
Simple PVR-addon" ( https://github.com/afedchin/xbmc-addon-iptvsimple ).
Not that complicated for the user.

A Question:

how does a stream-link needs to be formed to work with your app and
liveplayer?
I tried different sources today, and always got error-messages like
"$invalidresponsecodeexeption response code 404" or
"$httpdatasourceexeption unable to connect..." . Any advise?


2015-07-27 21:17 GMT+02:00 Nick <notifications@github.com>:

**Comment by Fleker** [comment]
I'll take a look at the XMLTV format. It looks like a way to store all the
app data, not just programs. Right now channel data is just being stored as
JSON, but I could potentially build a parser for everything. Alternatively,
each channel could choose an additional XMLTV file which can be updated
concurrently. What do you think should happen?

The channel player uses the newest iteration of Google's ExoPlayer (
http://google.github.io/ExoPlayer/) to play HLS and m3u8 streams. It looks
from the error that the stream url either does not exist, or is not the raw
stream file. You can try opening that same url in VLC Player or other media
players and see whether that stream can even be played. Look at some of the
suggested stream URLs.

**Comment by HerrSchultze** [comment]
"
*...each channel could choose an additional XMLTV file which can be updated
concurrently.*"
This option seems to be the more clean solution.


"... It looks from the error that the stream url either does not exist, or
is not the raw
stream file. You can try opening that same url in VLC Player or other media
players and see whether that stream can even be played. Look at some of the
suggested stream URLs. ..."
I already checked this before. The links are working in VLC and LazyIPTV
(+MX player).
Here 3 examples.:

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
[
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1456000,RESOLUTION=852x480,CODECS="avc1.77.30,
mp4a.40.2"  ]


*http://zdf-hds-de-f.zdf.de/i/de13_v1@147090/index_1456_av-p.m3u8?sd=10&dw=0&rebase=on
<http://zdf-hds-de-f.zdf.de/i/de13_v1@147090/index_1456_av-p.m3u8?sd=10&dw=0&rebase=on>*
resp.

*http://zdf-hds-de-f.zdf.de/i/de13_v1@147090/index_1456_av-p.m3u8
<http://zdf-hds-de-f.zdf.de/i/de13_v1@147090/index_1456_av-p.m3u8>*

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
[  #EXTINF:-1,Euronews De  ]

*http://fr-par-iphone-2.cdn.hexaglobe.net/streaming/euronews_ewns/14-live.m3u8
<http://fr-par-iphone-2.cdn.hexaglobe.net/streaming/euronews_ewns/14-live.m3u8>*


----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
[  #EXTINF:-1 tvg-id="0010" group-title="Deutsch"
tvg-logo="0010.png",[COLOR orange]VOX[/COLOR]   ]

*http://pvr.tvip.ga/0010.m3u8|X-Forwarded-For=81.17.18.50
<http://pvr.tvip.ga/0010.m3u8|X-Forwarded-For=81.17.18.50>*


---------------------------------------------------------------------------------------------------------------------------------------------------------------------------

2015-07-28 20:20 GMT+02:00 Nick <notifications@github.com>:

**Comment by HerrSchultze** [comment]
---------- Forwarded message ----------
From: Herr Schultze <matthias.lietz@gmail.com>
Date: 2015-07-28 21:55 GMT+02:00
Subject: Re: [CumulusTV] Channel list and editing (#2)
To: Fleker/CumulusTV <
reply@reply.github.com
>


"
*...each channel could choose an additional XMLTV file which can be updated
concurrently.*"
This option seems to be the more clean solution.


"... It looks from the error that the stream url either does not exist, or
is not the raw
stream file. You can try opening that same url in VLC Player or other media
players and see whether that stream can even be played. Look at some of the
suggested stream URLs. ..."
I already checked this before. The links are working in VLC and LazyIPTV
(+MX player).
Here 3 examples.:

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
[
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1456000,RESOLUTION=852x480,CODECS="avc1.77.30,
mp4a.40.2"  ]


*http://zdf-hds-de-f.zdf.de/i/de13_v1@147090/index_1456_av-p.m3u8?sd=10&dw=0&rebase=on
<http://zdf-hds-de-f.zdf.de/i/de13_v1@147090/index_1456_av-p.m3u8?sd=10&dw=0&rebase=on>*
resp.

*http://zdf-hds-de-f.zdf.de/i/de13_v1@147090/index_1456_av-p.m3u8
<http://zdf-hds-de-f.zdf.de/i/de13_v1@147090/index_1456_av-p.m3u8>*

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
[  #EXTINF:-1,Euronews De  ]

*http://fr-par-iphone-2.cdn.hexaglobe.net/streaming/euronews_ewns/14-live.m3u8
<http://fr-par-iphone-2.cdn.hexaglobe.net/streaming/euronews_ewns/14-live.m3u8>*


----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
[  #EXTINF:-1 tvg-id="0010" group-title="Deutsch"
tvg-logo="0010.png",[COLOR orange]VOX[/COLOR]   ]

*http://pvr.tvip.ga/0010.m3u8|X-Forwarded-For=81.17.18.50
<http://pvr.tvip.ga/0010.m3u8%7CX-Forwarded-For=81.17.18.50>*


---------------------------------------------------------------------------------------------------------------------------------------------------------------------------

2015-07-28 20:20 GMT+02:00 Nick <notifications@github.com>:

**Comment by Fleker** [comment]
I'll get into integrating xmltv support soon.

As for the links provided, only http://fr-par-iphone-2.cdn.hexaglobe.net/streaming/euronews_ewns/14-live.m3u8 seems to play on my phone. The others say they cannot.

I'm not doing any fancy parsing or URL forwarding right now. It takes whatever URL is included and interprets that as a video stream. Perhaps those stream types don't work on Android or I need to insert special rules to generate the correct URL.

**Comment by HerrSchultze** [comment]
"...The others say they cannot.." Where do you live actually? Could
"geoblocking" be an issue in your case (especially the ZDF link)? I'am
pretty sure of that.
//*Cause, "fancy" is not really the correct **description for the
stream-format, used by the official stream of the second largest TV station
in Germany... 😂 (it's a 110.000.000 people market only in Germany, Austria
and Swiss - and not the poorest countries).*
As I said before, "LazyIPTV" app (on Android TV) has no problems with the
streams. Ignore the thrown out "404" errorcode, it leads to the wrong
direction.

Anyway, the description of the exoPlayer is nice. Especially the support
for HEVC. Here in Berlin, the DVB-T2 HD (HEVC, 1080p) service will start in
spring.


---------------------

Forget the 3.stream (Vox), I made a mistake, sendig the wrong link. Sorry
for that.


best regards

M.



2015-07-28 22:05 GMT+02:00 Nick <notifications@github.com>:

**Comment by Fleker** [comment]
I'm in the US. Geoblocking certainly could be an issue as to why I can't view certain streams. Additionally, links like http://pvr.tvip.ga/0010.m3u8%7CX-Forwarded-For=81.17.18.50 seem to give me a 404 if I visit it directly though it seems like it should be parsed into a different URL. I don't know how I'm supposed to interpret a stream like that, and as-is returns a 404.

**Comment by HerrSchultze** [comment]
You're right. The "
http://pvr.tvip.ga/0010.m3u8%7CX-Forwarded-For=81.17.18.50" stream is
broken. According to the website, they had a dns-attack problem today - and
now there is a new channel list. Kind of my fault, I sent a dead link.

Tomorrow I have more time then today, and will insert more channels to find
out whats working for me.

According to the web, the "live app" seems do be a very "sensitive" app. ;)



Am 28.07.2015 23:27 schrieb "Nick" <notifications@github.com>:

**Comment by Fleker** [comment]
Ah. If that link is down, and another is geoblocked, then it does work on my phone and thus should work in the app. One of your links did load, so I'll try that on my side and see if it works.

**Comment by HerrSchultze** [comment]
Hi,

I tried some hours with the app.:


*1) Channels and Streams*

---------------------------------------------------------------------------------------------------------------------------------------------------------

*This 3 streams are working with your app:*

TVI (Portugal)
http://noscdn1.connectedviews.com:1935/live/smil:tvi.smil/playlist.m3u8


PHOENIXHD (German documentary channel)
http://teleboy.customers.cdn.iptv.ch/1122/index.m3u8


Sport 1 Germany
http://streaming-hub.com/tv/i/sport1_1@97464/index_1300_av-p.m3u8?sd=10&rebase=on


-------------------------------------------------------------------------

*This streams do not work with your app:*


Arte Ger/France (Both adresses refer to the same source)
http://pebbles107-lh.akamaihd.net/i/artede_1@97463/index_1300_av-p.m3u8|X-Forwarded-For=81.17.18.50

http://pvr.tvip.ga/0011.m3u8|X-Forwarded-For=81.17.18.50



Canal 2 Internac. Nicaragua
rtmp://162.244.81.181:1935/live//Stream1

RTP INTERNACIONAL (Portugal)
http://rtp-pull-live.hls.adaptive.level3.net:80/liverepeater/rtpi_5ch120h264.stream/livestream.m3u8

--------------------------------------------------------------------------

*Thoughts:*

It is strange that some links do not work.

- I've learned, that the Exoplayer does not support "rtmp", this explaines
"Canal 2". Quite sad, a lot of streams come as rtmp. Any workaround?

- Any Problems with HLS? (the "RTP" streams i.E.)?

- Cumulus seems to have problems with XFF, correct? A lot of
stream-adresses use proxies. Especially, if it comes to that (very
attractive "grey area"-) inofficial streams, cord cutters often looking for.


--------------------------------------------------------------------------------------------------------------------------------------------------------


*2. Abnormalities*

- Please check the formatting of the "rows" when user adds a channel. I
Guess the stream URL-row is formatted as "text"? Android wants to be polaid
and is helping me with my Orthographie. If I insert a "dot" an a letter
follows, Android inserts a "space".  😉   This is kind of a pain,
especially while the edit-function is broken.

- Live channel app seems to have problems.:

   - Sometimes it tries to connect to "unselect" marked channel.
   - Hand-over from cumulus to live player is a bit lame. Sometimes
   Tv-screen shows a large green android while open the player.
   - Sream-opening is slow  (compared to other apps, using the same stream).
   - Streamquality is really low at Phoenix-channel and "overscaled" (?).
   Compared to same channel at VLC or LazyIPTV-App or IPTV-player.
   - after manually stopping live-player-app and newstart with empty cache,
   it works for a little while better.


-------------------------------------------------------------------------------------------------------------------------------------------------------


*3. General*

Regarding "testing" with VLC Player on Android. I used to "love" this
player, but regarding stream-playing, it's not the best option anymore.
Have a look at the "Sport 1" Stream (
http://streaming-hub.com/tv/i/sport1_1@97464/index_1300_av-p.m3u8?sd=10&rebase=on
)  --> your app is able to play it, VLC say's NO.
Maybe ists better to try apps like "IPTV", "LazyIPTV" + MX Player (correct
configured), Imho.

https://play.google.com/store/apps/details?id=com.lazycatsoftware.iptv

https://play.google.com/store/apps/details?id=ru.iptvremote.android.iptv


attached a short playlist.





2015-07-29 0:23 GMT+02:00 Nick <notifications@github.com>:

**Comment by Fleker** [comment]
I'll check what's going on with the streams that don't work soon.

As I'm currently using ExoPlayer to render all of the streams, RTMP is not supported. I don't know how much work will go into supporting this format, but I'll investigate it.

HLS streams should work without any issue. 

I'm not too sure how well the player supports XFF but I'm going to guess that it doesn't. I can investigate this as well but I don't know how much time it'll take to implement it.

I'll fix the dialog box problems. (See #7)

Yeah, the green android is going to become a custom buffering screen.

Stream quality and speed are ultimately set by the player. I'll see if I can force some of it to change, but I don't want to go down the "implement a custom video player" route.

Thanks for the app suggestion. I've been using VLC since I know if a stream works there it'll work whereas an app with more format support may not work on the TV.

**Comment by Fleker** [comment]
I've tested streams suggested in this thread and have posted personal results. (Using version 1.1-r1 on the ADT-1)

http://zdf-hds-de-f.zdf.de/i/de13_v1@147090/index_1456_av-p.m3u8 does **NOT** work
Euronews De **DOES** work
http://pvr.tvip.ga/0010.m3u8%7CX-Forwarded-For=81.17.18.50 does **NOT** work
TVI (Portugal) **DOES** work
PHOENIXHD **DOES** work
Sport 1 Germany **DOES** work
http://pvr.tvip.ga/0011.m3u8%7CX-Forwarded-For=81.17.18.50 does **NOT** work
RTP Internacional **DOES** work

The reasons why certain links don't work could be because they are not currently valid, region blocking, or other reasons which are not fixable through the app. 

This thread can remain for discussing the particulars of some of these streams, though I have also opened other issues for notes you have made about the app.

**Comment by HerrSchultze** [comment]
Hallo Nick,

I've installed 1.1-r2.

I like it.

- The googledrive-integration is elegant.
- The scary Android /while buffering) is gone - your "please wait.."-page
is more charming.


*Issues:*
1.) I've realized, that the "*live channel app*" has some strange behavior.
It does not refresh the data (given by cumulus) at start. It remembers the
last status (for instance when it was last time trying to connect to a
stream).
This results into:

- if there was once a connection-error, live-channel gives always a new one
(it does not matter if the channel works or not);
- Error 403 messages (sometimes),

- it does not care for changes in the Data, given by Cumulus.:
-> Try to change the data of one stream in the Json-file and look what
happens!
-> After seeing the result, go to the "Live TV" Options und refresh in
"Channel-settings" (Kanäle einrichten). Result? Start live-tv again. Result?
-> Now try to change 2-3 Cahnnels incl. the channel number. Use an
"old"/already used Channelnumber too. Result?
-> Start live-tv again. Result?
-> Now try refreshing the "Channel-settings" (Kanäle einrichten).
-> Result is still unpleasant.

Maybe you should make Cumulus to send an order to Live-tv, to reset all
settings regarding Cumulus at start (and load everything new). Guess this
could help.


2) I still have questions regarding the channel-numbers, but I will test a
bit more.

best regards

M

2015-08-01 8:58 GMT+02:00 Nick <notifications@github.com>:

**Comment by Fleker** [comment]
I added #17 with regards to the issues you seem to be having.

**Comment by HerrSchultze** [comment]
Hallo Nick,

I've stability problems with 1.2.

- App crashes sometimes when Selecting "Go to live Channels" at the menue.
It's shooting up "Live channels" too. Need to restart my NP.
- 1.2 does not accept the Json file after inserting own channel's (via
editor).
- Selecting (Loading) an alternative Json when choosing "Swich Google drive
file" fails.


best regards

M.

2015-08-04 21:53 GMT+02:00 Nick <notifications@github.com>:

**Comment by Fleker** [comment]
I can't reproduce the Live Channels issue. Would you be able to share your
json file?

As to the other issues, I'll investigate those.

**Comment by HerrSchultze** [comment]
find attached two json files. (The app created a third one while crashing -
I cant send cause it's a zero-byte file. See attached screenshot.)

best regards

M.

2015-08-10 21:49 GMT+02:00 Nick <notifications@github.com>:

> I can't reproduce the Live Channels issue. Would you be able to share your
> json file?
>
> As to the other issues, I'll investigate those.

**Comment by Fleker** [comment]
I don't think you can attach files to issues. It's best to email them
directly to me: handnf@gmail.com

Thanks

**Comment by Fleker** [comment]
Good evening,
I have created issue #26 to fix the edit channels bug. 

With regards to problems switching drive files, I have not seen this issue personally. I am looking at the logs at the same time and it does take some time for the process to complete. If you wait a little bit between switching, it might not be a problem.

With regards to crashing, I haven't come across the same problem but I did look at a few crash reports that I did then fix. This might be the same problem that will now be fixed. (Check for `1.2.1`)

And currently there is no support for rtmp streams.

**Comment by HerrSchultze** [comment]
Thanks for your reply (Good evening is funny, here it was 08o'clock in the
morning 😂  )

I will check again.

Regarding rtmp: I know, I just use the same "*.json" since my fist
installations, just to test.

best regards

M.

2015-08-13 8:01 GMT+02:00 Nick <notifications@github.com>:

**Comment by Fleker** [comment]
"Hello,

I still have problems with the *.json file. I take it from google drive, edit it and copy it back. Cumulus does not realise my changes. Strange. Even if I tell it, to look at the file again.

I use this editor (chrome-addon) jsoneditoronline.org
Find attached a *.json file.

What about your plannings to support "*.m3u" ? 

Did you ever think about a plugin/interface to support DLNA/upnp server like "Serviio"? Would be a 'unique selling proposition', considering that at the moment only Vimu-player supports that feature. 
Supporting "Serviio" would have the advantage to cover up weaknesses of ExoPlayer while supporting hardware-based live-stream-transcoding - especially when it comes to "*.ts" or some strange rtmp streams. User may also avoid to install an udxpy at their router or NAS.

http://serviio.org/component/content/article/10-uncategorised/66-api"

Make sure you change the modified attribute. Increment it by at least one so the software knows it changed.

M3U should work with the current player.

For plugins beyond the current player, it's currently on the roadmap. Plugins  should eventually be able to link to a custom player service that they run.

**Comment by HerrSchultze** [comment]
"..Make sure you change the modified attribute.,," Sry, I dont get it.
Perhabs my english is not well enough.

{
      "number": "101",
      "name": "ISS Stream",
      "logo": "
http://static-cdn1.ustream.tv/i/channel/picture/9/4/0/8/9408562/9408562_iss_hr_1330361780,256x144,r:1.jpg
",
      "url": "
http://iphone-streaming.ustream.tv/uhls/9408562/streams/live/iphone/playlist.m3u8
",
      "splashscreen": "",
      "genres": "TECH_SCIENCE"
    },
    {
      "number": "102",
      "name": "Sic",
      "logo": "",
      "url": "
http://noscdn1.connectedviews.com:1935/live/smil:sic.smil/playlist.m3u8",
      "splashscreen": "",
      "genres": "ENTERTAINMENT"
    },





2015-08-17 23:59 GMT+02:00 Nick <notifications@github.com>:

**Comment by Fleker** [comment]
Newer versions of the app use a slightly different structure for files. They have an parent attribute called `modified` which is a timestamp of the last time modified. If you increase it when editing, it'll let the system know which version is newer and pick that one.

    {"channels":[{"number":"100",
         "name":"NASA Public",
         "logo":"http:\/\/static-cdn1.ustream.tv\/i\/channel\/live\/1_6540154,256x144,b:2015071514.jpg",
         "url":"http:\/\/iphone-streaming.ustream.tv\/uhls\/6540154\/streams\/live\/iphone\/playlist.m3u8",
          "splashscreen":"","genres":"TECH_SCIENCE"
    }],
    "modified":1439213690025,
    "possibleGenres":["ANIMAL_WILDLIFE","ARTS","COMEDY","DRAMA","EDUCATION","ENTERTAINMENT","FAMILY_KIDS","GAMING","LIFE_STYLE","MOVIES","MUSIC","NEWS","PREMIER","SHOPPING","SPORTS","TECH_SCIENCE","TRAVEL"]}

**Comment by HerrSchultze** [comment]
Ah. I've got it.
Am 18.08.2015 01:04 schrieb "Nick" <notifications@github.com>:

**Comment by HerrSchultze** [comment]
Hello Nick,
same problem with 1.3.0
Still not working after editing the *.json file in an editor. Even after
modifying the attribute, the app still does not care. For "refresh data", I
get an "Done", but it did'nt. So I deleted the file in googledrive,
restarted the app and asked for sync. Nothing happens. When going to
"Refresh data - cloud to local" the answer is "Invalid drive file - choose
a different file".

Its not depending of/on the channel I inserted. (Nothing to do with the
wrong Channel-Logo or ...) .
Next, I tried to "switch google drive file". Result: "..wait until drive
service is avtive".

This *.json file thing is strange and seems to be complicated - the way it
is configured now.. Maybe you could create a plugIn for "reading" classical
"*.m3u" files.

best regards

M.

2015-08-18 1:34 GMT+02:00 Herr Schultze <matthias.lietz@gmail.com>:

**Comment by Fleker** [comment]
Hi. I cannot seem to replicate your behavior. I am able to edit a json text file, increment the `modified` attribute, then be able to `Refresh` the content to load the new channels. 

You're saying that you do that, but when you go to "view channels" you don't see the channels have been modified?

The app has to create a service which connects to Google Drive. When you get the "Wait until the drive service is active" message, it means that service isn't active yet. It seems like there's a problem on your device where it is not connecting to Google Play Services in the app.

I'm going to add a patch which will be more transparent about the Google Play Services client. It should be out later tonight or tomorrow.

When you say "read" `.m3u` files, you mean when the system opens an `m3u` link it can open in this app? How would an Android TV user come across a link of this type?

The `json` format is used to store and read more than one channel, plus store other attributes related to the channel that aren't obvious just from the URL.

**Comment by alanmcramer** [comment]
I find when editing the json file on my Mac, it will not work in the app. If I edit the file on a windows machine using Notepad, works perfectly.

**Comment by Fleker** [comment]
That's a fascinating observation. @HerrSchultze are you using a Mac to edit the file?

Are you guys syncing the files and editing them locally or opening them in a web browser and editing them there?

**Comment by alanmcramer** [comment]
In both my cases, I'm using the Google Drive app for Windows and Mac respectively to sync files back and forth with the Google Drive folder. I have also used a text editing app directly in Google Drive via chrome web browser to no avail.

**Comment by HerrSchultze** [comment]
Hi Nick,

I'am using a Windows PC for editing. The editor is an
Google-Chrome-extension.
Anyway, your last changes (in 1.31 or 1.3.2 ?) made it better. Now it
accepts the edited *json. But still uncomfortable.

Please take away the new "Google Play Service..." windows. ;)

best regards

M.

2015-09-06 13:32 GMT+02:00 Alan Cramer <notifications@github.com>:

**Comment by Fleker** [comment]
No idea @alanmcrammer. Can't figure out a reason why it didn't work on one OS and not the other. Plus I'm developing in windows so I can't really test this.

@herrschultze I'm glad to hear it's working for you again. I agree the raw editing is not a great solution and I'd like to remove any friction.

Does the loading dialog obstruct your activity? Does it take a while to discuss?
