### ISSUE TITLE
I'm not able to add more channels

### ISSUE THREAD

**Issue by hprades** [Fleker/CumulusTV#222]
Hi, 

I'm using version 1.6.8 and I have 21 streams in the app and when I try to add one more, it doesn't show up in the list. 

And one more  thing, all channels appear in the added order in the listing, is there any way to sort them by number? In the live channels on ATV the list shows up in the right order.

**Comment by Fleker** [comment]
There were a few issues with Google drive sync. They are being ironed out.

I can probably add an option to reorder the channel list.

**Comment by Fleker** [comment]
Should be fixed in the latest beta.

**Comment by hprades** [comment]
Hi,

Since the app crashes as soon as I launch it on my phone, there's no way to check it :(

It happens since yesterday's update.

**Comment by Fleker** [comment]
Sorry to hear that. I'll take a look at crash reports and see what is
happening. I do think I have an idea already though.

**Comment by Fleker** [comment]
Phone issue should be fixed in 1.7.3, as should Google Drive
