### ISSUE TITLE
epgUrl parameter does not work properly on Mi Box

### ISSUE THREAD

**Issue by nicco** [Fleker/CumulusTV#223]
In my json I've added:

`"epgUrl":"http:\/\/tvprofil.net\/xmltv\/data\/rai-1.it\/weekly_rai-1.it_tvprofil.net.xml"`

to a channel but the modification is not displayed when I edit the channel in cumulus tv and the channel disappeared from live channels

**Comment by Fleker** [comment]
Noted.

**Comment by nicco** [comment]
I'm still having the same issues. Is it possible to have an example url of a file that works?

**Comment by Fleker** [comment]
I do not have one that actually works with a particular channel.

**Comment by nicco** [comment]
Should it be a single channel xmltv? I mostly wonder with what you did test it so that I can make mine accordingly!
