### ISSUE TITLE
v1.7.1 on mi box - continuous crashes

### ISSUE THREAD

**Issue by nicco** [Fleker/CumulusTV#227]
I updated my mibox to 1.7.1. 
The app looks overall very fast, by far the best experience I've had with IPTV on Android TV. 
Changing channels is now extremely fast and the quality of video is excellent.

That said I now have an issue. Cumulus keeps crashing every second and I have to phisically turn off  the box to exit live channels.

**Comment by Fleker** [comment]
I'll be making fixes based on crash reports. Thanks for the info.

**Comment by Fleker** [comment]
Updated.
