### ISSUE TITLE
Wrong splashscreen shown between channels.

### ISSUE THREAD

**Issue by nextux** [Fleker/CumulusTV#228]
Changing channels up and down in Sony Streaming Channels app on Android 5.1.1 shows wrong splashscreen.  It seems to be showing the splashscreen for the previously shown channel not the channel coming up.  1.7.1 seems to be showing the channels a lot quicker than previous versions so I am unsure if this splashscreen is still required.  Would be good to disable this altogether, or just show a simple spinning circle while loading the stream.  Would simplify the Json a bit removing the splashscreen element.  Maybe this needs to be a user setting?

"Disable splashscreen"

**Comment by Fleker** [comment]
Yes, I think I'll remove the splashscreen.

**Comment by Fleker** [comment]
The problem is that the splashscreen shows up when tuning when the channel data isn't loaded until afterward, leading to this discrepancy. Removing the splashscreen would be a temporary solution until I can find a better way to get this info.
