### ISSUE TITLE
M3U Url?

### ISSUE THREAD

**Issue by joq3** [Fleker/CumulusTV#229]
Hi,

Just downloaded the latest version, using it on my Mi Box. But nothing happens when I put in my M3U url. I have tried with the URL my provider gives me. Which links to a download of an m3u file.

Have tried waiting for a long time, but no difference!

**Comment by Fleker** [comment]
Are you able to get the JSON file? It should have the link information.

**Comment by joq3** [comment]
I just put in the URL and press update, takes me back to the start screen of Cumulus and nothing happens. If I go to the URL again, there is no URL set at all.
What do you mean with JSON file?

**Comment by Fleker** [comment]
There's currently no mechanism for viewing these URLs. It's probably
something I can build for the next beta.

If you're syncing with Google Drive, the data file could be useful to see,
to verify the data was actually added.

**Comment by joq3** [comment]
What kind of URL's does it support now?

The URL I try with looks like this:
http://linktoprovider.link:8080/get.php?username=xxxxxxxx&password=xxxxxxxxx&type=m3u_plus&output=ts

**Comment by Fleker** [comment]
It should work with any m3u-formatted file. It looks like that's what you
get. Can you look at what the file itself looks like? Is it M3U-formatted?

**Comment by joq3** [comment]
I have tried with two different versions, one is .ts links and the other is .m3u8 links. Looks like this:

`#EXTM3U
#EXTINF:-1 tvg-id="" tvg-name="########   Sweden   ########" tvg-logo="http://xxxxxx/sweden.png" group-title="Sweden",########   Sweden   ########
http://xxxxxx/xxxx.ts
#EXTINF:-1 tvg-id="SVT1 SE" tvg-name="SVT1 HD SE" tvg-logo="http://xxxxxxx/svt1.png" group-title="Sweden",SVT1 HD SE
http://xxxxx/xxxx.ts`

And the other one ends with .m3u8 instead of .ts (which doesn't work either).

**Comment by cumulususer** [comment]
Same thing happens to me. I click update and nothing happens. When i go back, the URL has disappeared. 

The URL i'm entering looks something like this:

http://xxx:4545/get.php?username=xxxx&password=xxx&type=m3u_plus&output=mpegts

When using chrome, it'll just download an m3u playlist for me.

**Comment by omygolly** [comment]
Same problem here, on MIBOX. I have also tried opening the file in explorer and choosing Create a channel, but it wont't work either. Neither does Google Drive import. Sync is fine but won't recognise the channels (I used the demo ones from the documentation) when I import.

**Comment by Fleker** [comment]
*Note to add more documentation*

**Comment by knoopx** [comment]
I can add URLs but nothing happens after

**Comment by Fleker** [comment]
So you link to a URL, click update, then return to the main activity? Then
if you select the link card again, do you see that URL in the list?

**Comment by knoopx** [comment]
Exactly, however no channels are found and there's no kind of feedback of what happens.i see you did some commits today, I'll try to build latest HEAD and debug what happens

**Comment by Fleker** [comment]
I may not have a lot of feedback, but I did push some fixes last night that
should improve the experience.

**Comment by Fleker** [comment]
Documentation is more detailed.
http://cumulustv.herokuapp.com/docs/IPTV_Channels/Linking_to_M3u_Playlist.html
