### ISSUE TITLE
epgUrl parameter triggers CumulusTV crash

### ISSUE THREAD

**Issue by nicco** [Fleker/CumulusTV#234]
Hi, I've added the following XMLTV url to a channel in my json

http://tvprofil.net/xmltv/data/rai-1.it/weekly_rai-1.it_tvprofil.net.xml

this triggers a crash of CumulusTV when importing the channels in Live channels and when opening the CumulusTV.

I've submitted my crash reports

**Comment by Fleker** [comment]
Interesting. Thanks for reporting it.

**Comment by Fleker** [comment]
The problem is in the data. One or more programs don't have an icon.

**Comment by nicco** [comment]
Thanks so it's live channels that is crashing?

**Comment by nicco** [comment]
Is there a way to see the logs? I'm trying to importing different ones but it keeps crashing

**Comment by Fleker** [comment]
If you connect your computer to the TV, you can view logs over ADB.

**Comment by nicco** [comment]
also my mibox?

**Comment by Fleker** [comment]
Yes connect your mi box to your computer over ADB to read logs. 

Though it seems like your source has incomplete data and that's causing the problem.

**Comment by nicco** [comment]
Now is to figure out what is missing and then why it's missing! Have you tried any XMLTV generation tool that works for you?

**Comment by Fleker** [comment]
It's specifically missing an image for the program. The image is null,
causing the source link field of the image class to throw a null pointer
exception.

**Comment by nicco** [comment]
Thanks but in a 217 megabyte xmltv file they are hard to spot :)

**Comment by nicco** [comment]
Created a custom xmltv. It seems to work but cumulus tv keeps crashing with this exception:

`01-21 01:29:17.664  6962  6962 D CumulusTvTifService: Play program Tg1 notte null
01-21 01:29:17.664  6962  6962 D AndroidRuntime: Shutting down VM
01-21 01:29:17.665  6962  6962 E AndroidRuntime: FATAL EXCEPTION: main
01-21 01:29:17.665  6962  6962 E AndroidRuntime: Process: com.felkertech.n.cumulustv, PID: 6962
01-21 01:29:17.665  6962  6962 E AndroidRuntime: java.lang.NullPointerException: uriString
01-21 01:29:17.665  6962  6962 E AndroidRuntime: 	at android.net.Uri$StringUri.<init>(Uri.java:475)
01-21 01:29:17.665  6962  6962 E AndroidRuntime: 	at android.net.Uri$StringUri.<init>(Uri.java)
01-21 01:29:17.665  6962  6962 E AndroidRuntime: 	at android.net.Uri.parse(Uri.java:437)
01-21 01:29:17.665  6962  6962 E AndroidRuntime: 	at com.felkertech.cumulustv.tv.CumulusTvTifService$RichTvInputSessionImpl.onPlayProgram(CumulusTvTifService.java:266)
01-21 01:29:17.665  6962  6962 E AndroidRuntime: 	at com.google.android.media.tv.companionlibrary.BaseTvInputService$Session.playCurrentProgram(BaseTvInputService.java:597)
01-21 01:29:17.665  6962  6962 E AndroidRuntime: 	at com.google.android.media.tv.companionlibrary.BaseTvInputService$Session.playCurrentContent(BaseTvInputService.java:556)
01-21 01:29:17.665  6962  6962 E AndroidRuntime: 	at com.google.android.media.tv.companionlibrary.BaseTvInputService$Session.playCurrentChannel(BaseTvInputService.java:658)
01-21 01:29:17.665  6962  6962 E AndroidRuntime: 	at com.google.android.media.tv.companionlibrary.BaseTvInputService$Session.playCurrentContent(BaseTvInputService.java:552)
01-21 01:29:17.665  6962  6962 E AndroidRuntime: 	at com.google.android.media.tv.companionlibrary.BaseTvInputService$Session.handleMessage(BaseTvInputService.java:225)
01-21 01:29:17.665  6962  6962 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
01-21 01:29:17.665  6962  6962 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
01-21 01:29:17.665  6962  6962 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5422)
01-21 01:29:17.665  6962  6962 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-21 01:29:17.665  6962  6962 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
01-21 01:29:17.665  6962  6962 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

**Comment by nicco** [comment]
Attaching the xmltv that I'm using
[epg.xml.txt](https://github.com/Fleker/CumulusTV/files/720796/epg.xml.txt)

**Comment by 9point6** [comment]
It would be good if there was a bit of documentation for an ideal xmltv file as it's not currently clear which elements are required (and in what format) by CumulusTV

**Comment by nicco** [comment]
agree, also maybe to suggest which library to use to generate it.

**Comment by Fleker** [comment]
Yes. Documentation is something I've been trying to build, and it'll be something I continue to work on.

**Comment by nicco** [comment]
And still I think that there is a bug in CumulusTv because this time the exception was not with Live Channels (stacktrace above)

**Comment by Fleker** [comment]
I will have to improve my error handling in the next version.

**Comment by Fleker** [comment]
nicco, I looked at your bug and it seems to not be an issue with the EPG Url, but with the media URL.

`01-21 01:29:17.664 6962 6962 D CumulusTvTifService: Play program Tg1 notte null`

This line is meant to print the channel name and the `mediaUrl` parameter. It looks like this parameter is null, so there is no video playing, leading to a crash. I can catch this and report an issue, but ultimately is something you will have to correct on your end.
