### ISSUE TITLE
m3u import, google drive crash latest beta

### ISSUE THREAD

**Issue by JeanPrendnote** [Fleker/CumulusTV#241]
using cumulus 1.7.2 beta and android tv 6.0.1 (Mibox) when trying to import m3u standard format :

#EXTINF:-1 tvg-ID="" tvg-name="channel" tvg-logo="" group-title="group 1",channel
http://s.xxx.com:8000/live/xxx/xxx/1.ts

cumulus is crashing , while :

#EXTINF:-1 ,channel
http://s.xxx.com:8000/live/xxx/xxx/1.ts

is working. maybe because some fields are empty ?

also google drive is not working anymore, it crash when you try to use it, i have tried to reset app datas already

i will try to send bugreports next time that i will use the app,

**Comment by Fleker** [comment]
Where are you importing from? Google drive? That currently isn't supported.

Should I make that more clear?

**Comment by JeanPrendnote** [comment]
No, from internal. It's 2 different crashs.

**Comment by Fleker** [comment]
I'll add both to the parser tests to see where the problem lies.

**Comment by Fleker** [comment]
There were two issues with the playlists.

The first is that the first line doesn't contain `#EXTM3U` to identify it as the correct format. This is required based on how the parser works at the moment.

The second is that empty strings were causing the parser to be too greedy and shift too many characters, causing the whole parser to fail. This bug has been corrected and both streams are added to tests.
