### ISSUE TITLE
[XMLTV] Icon shouldn't be required

### ISSUE THREAD

**Issue by davic-anime** [Fleker/CumulusTV#251]
Hi Fleker,
The ICON tag in the XMLTV parser shouldn't be required as most data suppliers such as gonix etc don't provide images in the data. If it's required by Live Channels maybe a possibility to use a default image from CumulusTV?

**Comment by Fleker** [comment]
It's not required by Live Channels, but currently required by the parser. I may need to rewrite that for more general support.

**Comment by Fleker** [comment]
In 1.7.5 there's a new XML parser that should not require icons
