### ISSUE TITLE
Support for multiple audio sources

### ISSUE THREAD

**Issue by davic-anime** [Fleker/CumulusTV#252]
Hi Fleker,
Is there a possibility to implement support for multiple audio sources that are in a .TS file?

I.e. a channel has multiple languages embedded into one stream such as dubs for Russian, German etc.

**Comment by davic-anime** [comment]
Or a way to specify which source to use in the json file.

**Comment by Fleker** [comment]
There is a way in Live Channels to select between multiple audio sources. This was brought up in #121. I don't know how difficult it may be to implement, so I'll have to do some research.

**Comment by davic-anime** [comment]
Looks like a duplicate issue then. I'll close this in favor of #121.
