### ISSUE TITLE
Support to import one XMLTV file for all channels.

### ISSUE THREAD

**Issue by shindycham** [Fleker/CumulusTV#257]
At the moment, it is possible to import epg data for one single channel. This is great if you have less than 20 channels or so. But if you have a big channel list with around 100+ channels this is very cumbersome.
I use http://www.webgrabplus.com/ as a epg grabber and it lists down all programm-data for all channels I have set up. The final result is a XMLTV file you can find attached below. (I compressed it for faster download).

[newguide.xml.gz](https://github.com/Fleker/CumulusTV/files/760966/newguide.xml.gz)

**Comment by loueradun** [comment]
Why did you close this issue?  I really think this would be an awesome enhancement.  Basically set up an episode guide URL to be monitored similar to the playlists and provide the ability to assign a guide ID to each station that correlates to the listing in the xmltv file.
