### ISSUE TITLE
CumulusTV crashes in loop when I open Live Channels

### ISSUE THREAD

**Issue by FezVrasta** [Fleker/CumulusTV#260]
I have a single M3U playlist loaded into CumulusTV (I created it on my smartphone, synced with gdrive to the CumulusTV app on my Shield TV).

Sometimes, when I go to open the Live Channels app, the CumulusTV app crashes (the Android dialog appears), if I click "ok", it crashes again and again in loop.

Once I manage to kill the Live Channels app, if I open the CumulusTV app, I see that my m3u playlist isn't loaded. I have to click "sync" few times and wait a minute to see it appear again.

I guess the problem is that my M3U playlist is loaded through an Heroku app (because I need to parse the playlist to fix some meta data), and it takes usually 15 seconds to load.

Any solutions for this problem?

**Comment by Fleker** [comment]
I have crash reporting set up, so I should see when the app crashes, although I don't know why there's an issue in your case offhand.

**Comment by loueradun** [comment]
I've been seeing the same issue.  Solution is to double tap the home button to bring up the task switch and close live channels, then open CumulusTV and wait 5-10 seconds for it to sync.  Then Live Channels works fine.  Seems you have to do this every time you reboot or resume the Android TV from sleep.

**Comment by loueradun** [comment]
I guess I should say that the above is a workaround, not exactly a "solution"...  This first started happening with version 1.7.3 by the way.

**Comment by Fleker** [comment]
Try the next update and let me know what happens.

**Comment by loueradun** [comment]
@Fleker If you are referring to 1.7.5, it has the same issue.

**Comment by Fleker** [comment]
This must be an issue related to syncing the first time. I think a potential solution would be to preload data in the system whenever there is a reboot.

**Comment by Fleker** [comment]
See #254
