### ISSUE TITLE
Restart is needed for new channels to appear

### ISSUE THREAD

**Issue by ejurgelionis** [Fleker/CumulusTV#265]
When I click "Redownload Channel List" I get "Data downloaded from Google Drive". Nevertheless, new channels appear in the app only when I restart the app.

**Comment by Fleker** [comment]
Yes that is a display but I encountered. The channels do exist, you just
can't see them. Should be an easy fix.

**Comment by ejurgelionis** [comment]
@Fleker BTW, the same applies to Live Channels. New channels do not appear there as well unless I restart the app.

**Comment by Fleker** [comment]
That's useful to know.

**Comment by Fleker** [comment]
The code should now force a redraw and Live Channels resync on every change
