### ISSUE TITLE
Not available on Google Play anymore

### ISSUE THREAD

**Issue by maddy-mad** [Fleker/CumulusTV#304]
Hi Admin,

We are unable to download the app from Google Play Store, below screenshot.

![image](https://user-images.githubusercontent.com/32452906/47063857-b1cf9280-d1fa-11e8-87a4-3f1323f72c2c.png)

**Comment by Fleker** [comment]
It looks like some apps were delisted due to some requirements in the play console. I've made those corrections and resubmitted the listing.

**Comment by maddy-mad** [comment]
Thanks, we can see now ... :)
