### ISSUE TITLE
Add TWiT as a sample

### ISSUE THREAD

**Issue by bgiesing** [Fleker/CumulusTV#32]
[TWiT.tv](http://twit.tv) is a great free streaming Tech Network airing 24/7 with new shows every day.

Here's the JSON I made to make it easier:
```JSON
{
  "channels":[
        {
            "number":"88",
            "name":"TWiT",
            "logo":"http:\/\/wiki.twit.tv\/w\/images\/thumb\/TWiT_Logo.svg.png\/487px-TWiT_Logo.svg.png",
            "url":"http:\/\/twit.live-s.cdn.bitgravity.com\/cdn-live-s1\/_definst_\/twit\/live\/high\/playlist.m3u8",
            "splashscreen":"",
            "genres":"NEWS,TECH_SCIENCE"
        }
    ],
    "modified":"1439728483656",
    "possibleGenres":["ANIMAL_WILDLIFE","ARTS","COMEDY","DRAMA","EDUCATION","ENTERTAINMENT","FAMILY_KIDS","GAMING","LIFE_STYLE","MOVIES","MUSIC","NEWS","PREMIER","SHOPPING","SPORTS","TECH_SCIENCE","TRAVEL"]
}
```

**Comment by Fleker** [comment]
Added in 1.2.6

**Comment by bgiesing** [comment]
@Fleker Just a couple of updates to this stream suggestion since I forgot to mention them:
1. Horizontal logo might look better in the Live Channels guide (seeing that most of the other apps are using horizontal logos also) Here's the link for it:
`http:\/\/wiki.twit.tv\/w\/images\/TWiT-horizontal.png`
2. You put the name as TWiT (This Week In Tech). I can't remember where but they have mentioned multiple times in the past that the network shouldn't be referred to as the name of the flagship show but only as either:
    - TWiT
    - TWiT.tv
    - The TWiT Netcast Network

**Comment by Fleker** [comment]
Thanks. Will integrate changes in next build.
