### ISSUE TITLE
Provide examples of Splashscreen

### ISSUE THREAD

**Issue by alanmcramer** [Fleker/CumulusTV#33]
I have had fun playing with this app the past few days.  I would really appreciate it if you were able to provide an example of compatible sizes for Splashscreen element.

**Comment by Fleker** [comment]
Custom splashes are just 1920x1080 image files. That's more on the deeper end of customization. For general use the generic splash is satisfactory and more interactive.

**Comment by bgiesing** [comment]
@Fleker I just tried using this URL for a splash (https://i.imgur.com/98Sf8vE.jpg) but it doesn't show up... Any ideas?

JSON:
```json
    {
      "number": "39",
      "name": "TWiT",
      "logo": "http://wiki.twit.tv/w/images/TWiT_Logo.svg.png",
      "url": "http://twit.live-s.cdn.bitgravity.com/cdn-live/_definst_/twit/live/high/playlist.m3u8",
      "splashscreen": "http://i.imgur.com/98Sf8vE.jpg",
      "genres": "NEWS,TECH_SCIENCE"
    }
```

**Comment by Fleker** [comment]
I don't know why that's occurring. Maybe it's a problem with the image or splashscreens were never fully implemented.

Are you using 1.5.x?

**Comment by bgiesing** [comment]
@Fleker Yep, the latest 1.5.3b

**Comment by Fleker** [comment]
Yeah I'm pretty sure that splashes were temporarily removed
On Apr 25, 2016 9:35 PM, "Brandon Giesing" <notifications@github.com> wrote:

@Fleker <https://github.com/Fleker> Yep, the latest 1.5.3b

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/Fleker/CumulusTV/issues/33#issuecomment-214581411>

**Comment by Fleker** [comment]
Nope code seems to be active, but I'm not querying the channels correctly

**Comment by Fleker** [comment]
ChannelSurfer appears to break the ordering I'd need to display splashscreens. I think I can fix it with some class extensions though.

**Comment by Fleker** [comment]
Fixed, will be in the next build

**Comment by Fleker** [comment]
https://github.com/Fleker/ChannelSurfer/issues/26
Adding to Channelsurfer as well
