### ISSUE TITLE
[URGENT] Impossible to pass setup

### ISSUE THREAD

**Issue by bgiesing** [Fleker/CumulusTV#34]
With the new version, it's impossible to exit setup unless you have a mouse (which most people dont) @Fleker

**Comment by Fleker** [comment]
Are you referring to the introduction screen? It should exit if you tap far
enough or press A on the last slide.

**Comment by bgiesing** [comment]
I have been pressing right, down, up, left, and select for minutes now.

Nexus player remotes don't have an A button

**Comment by Fleker** [comment]
Ah, I must've forgotten to add support for remotes. Okay. I will fix this
tonight and in the meantime remove the update. Thanks for letting me know.

**Comment by Fleker** [comment]
Test 1.2.8 and see how it goes
