### ISSUE TITLE
Companion application for Android mobile

### ISSUE THREAD

**Issue by alanmcramer** [Fleker/CumulusTV#38]
As a side project, it would be great if there was a companion application that would allow you to import streams from m3u or m3u8 into the json file held within your Google drive. Kind of like a cumulus TV editor to make it easy to copy and paste via android phone then fire up your Android TV for import.

**Comment by Fleker** [comment]
There's already somebody who is working on a web version. I can put you in touch with that person if you want.

Or are you referring to a mobile app?

**Comment by alanmcramer** [comment]
Mobile app to make it easier to import bits and pieces. Web app will be just as cool but I figured you have most of the code in place. You'd just need to make it mobile screen friendly and only be to add sources to a json file

**Comment by Fleker** [comment]
A mobile app would not be too difficult to add.

**Comment by Fleker** [comment]
I'll start looking at implementing this as it would certainly come in handy for testing streams (and opening them from mobile as well)

**Comment by Fleker** [comment]
This will be tested in 1.3.4

**Comment by alanmcramer** [comment]
App works really well on mobile.... What are you using to show the mini player on Android? Is it exoplayer or something else?  Reason I ask is one of the iptv channels works flawlessly on the mobile but continually buffers on the Android TV.

**Comment by Fleker** [comment]
The app on both the phone and TV are the same. Additionally, the mini
player shown in the "View Channels" option is the Exoplayer, but a much
smaller resolution. This smaller resolution is probably one reason why it
buffers much less. One stream file can have several HLS versions for sizes
/ bit rates.

**Comment by Fleker** [comment]
Has this been fixed? The player should be the same, and the app is on mobile, so I believe that this issue should be closed.
