### ISSUE TITLE
Open m3u files

### ISSUE THREAD

**Issue by Fleker** [Fleker/CumulusTV#39]
Allow the app to open this type of file, add it to your list, and let you configure properties.

This can open an intent in the New Channel activity and read the channel URL from an intent.

**Comment by chemstar** [comment]
i can see that m3u playlist is supported but i can't find a way in app how to import channels from such playlist. my file manager on stv doesn't list ctv as registered app for m3u or m3u8 files. could someone explain how to use it correctly?

**Comment by Fleker** [comment]
The app should be supported when you open one of those file types or just plain text. The Create a channel option should appear.
