### ISSUE TITLE
Allow users to import m3u files

### ISSUE THREAD

**Issue by Fleker** [Fleker/CumulusTV#40]
Maybe they don't open the file on their TV, but have it in their Drive. Let users import a file from Drive.

This can be an additional plugin.

**Comment by bgiesing** [comment]
I would open it from a file browser, so it should at least support it from
a local file.

On Mon, Aug 31, 2015, 3:47 PM Nick <notifications@github.com> wrote:

> Maybe they don't open the file on their TV, but have it in their Drive.
> Let users import a file from Drive.
>
> This can be an additional plugin.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Fleker/CumulusTV/issues/40>.
>



To unsubscribe click: <http://email.giesing.cf/u/eJwljjFvwjAUhH9NshXZ7zl-9uAhAdGBtKgdKBuyHTuJAKVyiSr_e9L0dLrp0911RkrroRzNtj7ME13PbThifj1cPlMBzVdWZ6zzW37pC9zNw3ban1L4bZrTj3pv2136KAS72_G26df0070cTEWSXKc8Z0oQ8x4JZAxhseg4l7ZMJoXvW14GGCNF2tIfyAHcgndRaZRRq4i68gIApeMIzGpbMQ0-sn9xzqOnSKjBcql9YBJFcI6WS2v9ph8fw-zWUw9TQP0E9oVFNQ>

**Comment by Fleker** [comment]
That would be #39.
