### ISSUE TITLE
Sony Bravia Android TVs doesn't includes Live Channels app

### ISSUE THREAD

**Issue by lardissone** [Fleker/CumulusTV#45]
Not sure if it makes any difference, but I can't get it to work.

Probably it works different?

There's another app (Pluto TV) that adds channels to the Streaming TV.

**Comment by Fleker** [comment]
All Android TV devices should work the same with respect to platform features and apps.

If you have Cumulus TV and Pluto TV, both should be accessible in the Live Channels app. The app only appears though if your device has setup live channels. Have you set up any live channels yet? In Cumulus TV, that would require you adding at least one stream.

If you go to the "Channel Sources" menu in Live Channels, you should see all the apps that can add Live Channels. When you click on "Cumulus TV", it should rescan and sync all the channels that you've added. Then, you have to go to the "Channel list" menu and select the channels that you want to appear (or pick all of them).

**Comment by lardissone** [comment]
You're right.

It doesn't includes Live Channels app, but you can modify streaming channels settings on main Settings.
And here you can see Cumulus and Pluto.

Thank you!

**Comment by alanmcramer** [comment]
Just purchased a Sony Bravia. It does operate slightly different.

When you go to Settings > Channel Setup > Streaming Channels > Cumulus TV > Setup you get the Grabbing your channels screen.  Upon completion the expected behavior is that going to Settings > Channel Setup > Streaming Channels > Show/Hide Channels should show a list of your channels via Cumulus. It doesn't show though. If Cumulus is installed on its own, the option for Show/Hide Channels isn't even there.  If you have Pluto TV installed, it will show only the Pluto channels.

**Comment by Fleker** [comment]
That's bizarre. What channels do you have set up? Is Sony's live channels
the same as the Android TV live channels?

**Comment by alanmcramer** [comment]
It seems similar. They call it Streaming Channels. When checking the apps
installed on the device, it is called Live Channels also version 7.3 (I
don't think Google's version is as high).

It also behaves a lot different to the standard live channels app.  Pushing
the middle button on the Sony remote does nothing within the app. You need
to go via the main Android TV settings cog as per my previous post. The
breadcrumbs posted above also are the exact way to "Customize Channel List"
on the Sony.

How does Cumulus TV "inject" the channels into the Live Channels app
normally?  Maybe Sony are storing their file in a different location. I'm
going to have a better play around tonight after work but if you could give
me an idea where to look that would be great.

Alan

**Comment by Fleker** [comment]
Channels are added through a database query to the Live Channels app. If
the package name is different, then this could be an issue.

I'm investigating this.

**Comment by BradleyRL** [comment]
CumulusTV worked fine on my Bravia, I could even customize the channel list, not using it right now since the channels I had are all dead now, will try tonight with the sample ones but im pretty sure cumulustv had no issues

**Comment by alanmcramer** [comment]
I know when I press "Open Live Channels" inside the app, I get a message at
the bottom to email you.

**Comment by Fleker** [comment]
Thanks for doing that. That's part of this investigation. Can you find the
package name for Sony's Live Channels app?

**Comment by alanmcramer** [comment]
Will do when I get home from work. Should be able to in around an hour or
two.

**Comment by alanmcramer** [comment]
After some digging around I found it...

com.sony.dtv.tvplayer

SonyTvPlayer.apk

**Comment by Fleker** [comment]
Great. Thanks!

I'm trying to resolve more issues with the Sony TV as well.

**Comment by alanmcramer** [comment]
Let me know what issues you want me to test. Happy to assist.

**Comment by Fleker** [comment]
Right now I'm planning on migrating to the channelsurfer library,
http://github.com/Fleker/channelsurfer, and there's a sample apk there I'm
using.

If you could use that apk and figure out what doesn't work, I can fix
problems for many live channels apps.

**Comment by alanmcramer** [comment]
I can't seem to find the sample apk. What folder will I find it in?

**Comment by Fleker** [comment]
You should be able to find it under releases

**Comment by alanmcramer** [comment]
Never mind. Had to switch to desktop mode on github to find it.

**Comment by alanmcramer** [comment]
Sample seems to be working perfectly. And now I happen to know my TV clock
is 5.0 seconds ahead.

In the settings area as mentioned above, ChannelSurfer Sample has a setup
option and it then shows and actives the two channels in the Show/Hide
Channels screen.

**Comment by alanmcramer** [comment]
Are there any specific issues that you need me to test with channelsurfer? If there a way to import Cumulus TV channel lists into ChannelSurfer? (Trying to prevent death by wife)

**Comment by Fleker** [comment]
They're different projects. Channelsurfer is the back end/player with
sample streams while Cumulus is for picking custom streams. They shouldn't
overwrite the other.

As for testing, I want to make sure the epg and streams are working.

**Comment by alanmcramer** [comment]
Can confirm that with ChannelSurfer both epg is working on the Bravia as well as streaming.  Both time and Big Buck Bunny are able to be viewed.

The EPG works really well with Sony's customised Program Guide app, when filtering "Streaming Channels".  I get hour blocks of "What Time is it? Currently Streaming" and "Big Buck Bunny" with the same sub caption.  Channel logos on the info bar show as an android head.

Within the Program Guide, the program displays a still image of a disco ball.  This is also displayed within Sony's customised "Discover" feature.
![img_20160116_123159](https://cloud.githubusercontent.com/assets/3284938/12369792/30c56346-bc4e-11e5-818d-78b436c1d465.jpg)
Standard Info Bar - When you change channel (snapped as the page was loading)
![img_20160116_123533](https://cloud.githubusercontent.com/assets/3284938/12369813/93b04a20-bc4e-11e5-84fd-eb510f37385d.jpg)
Extended Info Bar - When you press info
![img_20160116_123604](https://cloud.githubusercontent.com/assets/3284938/12369815/9aef872e-bc4e-11e5-8d2c-579f3d86db55.jpg)
Sony's Discover feature (Streaming channels)
![img_20160116_123626](https://cloud.githubusercontent.com/assets/3284938/12369816/9d8e7184-bc4e-11e5-93b7-ca8726a2db83.jpg)
Program Guide - Streaming Channels
![img_20160116_123747](https://cloud.githubusercontent.com/assets/3284938/12369817/a00cc64a-bc4e-11e5-9a1d-3e25f8b8863e.jpg)
Selecting a program within the program guide.

**Comment by Fleker** [comment]
I'm glad to hear that. When I integrate the library it should work on the
Sony.

**Comment by alanmcramer** [comment]
1.5 will be the first release with the library integrated?

**Comment by Fleker** [comment]
Yes I'm developing that in a separate branch and will merge once it's ready.

**Comment by 90integ** [comment]
Fleker i have the issue listed above, i have been using the cumulus tv app just fine until about two weeks ago it stoped streaming the channel information for each chanel so yesterday i reset all my apps by cleaning the data out and started over and pluto tv and the weather network loaded and stream to the live channels app fine, but cumulus tv on the grabbing your channels page of live channels shows them in the upper left corner loading and even gives a pop up saying to tick them in the channel list but the funny thing is cumulus tv stays under the new tab like it was not set up, and even says not set up, and will not stream the channels.  I have no idea whats going on and i have reset everything multiple times and no go.    Any advice would be greatly appriciated.

**Comment by Fleker** [comment]
It's a known issue; I'm working on it.

**Comment by 90integ** [comment]
Oh ok thanks for the heads up i just wasnt sure if it was wide spread or if
i was alone in this issue .

Thank you.
