### ISSUE TITLE
Miniplayer Expands

### ISSUE THREAD

**Issue by Fleker** [Fleker/CumulusTV#46]
Allow users to expand the miniplayer to actually stream the channel in the app.

**Comment by alanmcramer** [comment]
Should work similar to the YouTube app. Have the streamed channel appear at the top of the screen and when the phone is turned landscape, the video expands to fill the landscape view.

**Comment by Fleker** [comment]
This opens a new activity with any orientation

**Comment by Fleker** [comment]
Will be available through a new dialog button in 1.3.6 / 1.4.0
