### ISSUE TITLE
Are only HLS and MPEG-DASH supported?

### ISSUE THREAD

**Issue by Gfunk117** [Fleker/CumulusTV#52]
I am trying to add simple http m3u streams for custom channels but none are working.  I have an m3u livetv list from my http server and I remux my hdhomerun prime channels to h264 using vdr iptv plugin but I can not seem to get channels to play.  

Channels all play fine using mx player, vlc, kodi etc....

**Comment by Fleker** [comment]
Hi,
You can add each HLS stream to the app and it should play fine. What
happens when you try to add the stream URL? What happens when you try the
built-in player?

-Nick

**Comment by Gfunk117** [comment]
Thanks for the response.  Here some more info on my streams.  They are re-encoded on the fly from mpeg-2 to h264 mpegts.  Each channel is a separate .m3u live channel containing this: 

#EXTM3U
#EXTINF:-1,1 DISCOVERY-HD
http://mydyn.ip.net:3000/EXT/I-0-930-930

I host each of these .m3u on my apache webserver and added them as links:

http://mydyn.ip.net/discovery_channel.m3u

I added these as links in Cumulus but there is no preview on the built in player and my nexus player and adt-1 do not play the custom channels. This is the only way I could think of to get these to work with CumulusTV but no go.

Any help would be great :)

LOVE THE APP BTW!!!

**Comment by Fleker** [comment]
Thanks for the love! <3

At the moment, only HLS is supported. MPEG-DASH is currently not (but there's no reason it can't be, this will be added in the next update).

Additionally, there is planned but not implemented support for playlists. Right now each channel has to be manually entered.

Could there be a geoblocking issue? Those streams do not seem to play for me (USA).

**Comment by Gfunk117** [comment]
That stream is my personal HDHomerun Prime cable subscription stream so I
took out the valid IP/Dynamic IP.  I will try and research ffmpeg
outputting HLS m3u8 live streams.  I can't seem to figure out the ffmpeg
command line for re-encoding my input which is mpegts to hls/m3u8.

I know I could use wowza so maybe thats a solution...

**Comment by Fleker** [comment]
It looks like Homerun streams might work if I add MPEG-DASH support back to the app. I'll try to get something thrown together this week and get back to you.

**Comment by Gfunk117** [comment]
HDHomerun is just straight MPEG2 MPEG-TS.  Should be very easy to implement standard mgegts (mpeg transport streams).  But I am mainly using Cumulus as a remote TV application so I can adjust the bitrate to use livetv channels on mobile networks for less bandwidth.  I can give you a link via email to test a stream in vlc so you can see the container format.  My email is on my github profile.

**Comment by Fleker** [comment]
Hey there, 
Can you sideload 1.4-alpha 1 on your device and see if that improves anything? I think #53 should be fixed.

**Comment by Gfunk117** [comment]
Awesome.  I'll sideload it and test out the streams tmro.  Thanks a million for your fix!

**Comment by Fleker** [comment]
If it hasn't worked so far, try again once I get the new build published. The issue may be related to #65 and the app should now have more support for MPEG-TS (and MPEG-DASH) by checking different codecs per stream.

**Comment by Fleker** [comment]
New version is published. Let me know when you get a chance to test 1.4.1.

**Comment by Gfunk117** [comment]
Heyyyy sorry Nick ive been super busy I will try the updated apk tonight
and let you know if its working for regular mpegts streams
