### ISSUE TITLE
issue with streams

### ISSUE THREAD

**Issue by breadcan** [Fleker/CumulusTV#65]
Maybe it is not the app. I have a problem with some streams. They worked yesterday but now I got errors. Maybe because I switched to the beta? Installed Version is 1.4-alpha 2.

D/cumulus:TIS.S( 4865): Tuning to content://android.media.tv/channel/103
D/cumulus:TIS.S( 4865): Retrieved stream http://wdr_fs_geo-lh.akamaihd.net/i/wdrfs_geogeblockt@112044/index_3776_av-p.m3u8?sd=10&rebase=on
D/cumulus:TIS.S( 4865): Tune into content://android.media.tv/channel/103
D/cumulus:TIS.S( 4865): Found channel & start playing http://wdr_fs_geo-lh.akamaihd.net/i/wdrfs_geogeblockt@112044/index_3776_av-p.m3u8?sd=10&rebase=on
D/cumulus:TvInputPlayer( 4865): I'm born!
I/ExoPlayerImpl( 4865): Init 1.5.0
D/cumulus:TvInputPlayer( 4865): Prep HLS
D/cumulus:exoplayer( 4865): Idle
D/hwcomposer(  210): void update_freq(nvhwc_context*, int): boost frequency: gpu_min 153600, emc_min 4080
D/cumulus:exoplayer( 4865): Play when ready committed
D/cumulus:TIS.S( 4865): An error occurs!

https://drive.google.com/open?id=0B8NrUksLGljUU29YbmYzOVYtR2c

The arte stream still works.

I have the same streams in a m3u and they play fine on the Shield TV inside IPTV/mxPlayer.
https://drive.google.com/open?id=0B8NrUksLGljUc3hEcEM0VWFON2M

**Comment by breadcan** [comment]
hmpf, I missed the error line:

D/cumulus:TIS.S( 4865): com.google.android.exoplayer.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 503

**Comment by Fleker** [comment]
Hmm a 503 error means the website is currently unavailable. In fact, going to the main index (http://wdr_fs_geo-lh.akamaihd.net/), there seems to be a problem with the DNS finding this host. You might be able to figure out whether this is temporary or not.

**Comment by breadcan** [comment]
The stream from the url opens fine in other apps. The error message in the browser comes from the server and only from the root page. 

http://wdr_fs_geo-lh.akamaihd.net/i/wdrfs_geogeblockt@112044/index_3776_av-p.m3u8?sd=10&rebase=on
I can open the stream directly in chrome on Android for example. And the urls works fine on Android tv in IPTV for example. And they worked in Cumulus too. I switched to the testing version, maybe there is the problem. I'll check the playstore version tomorrow. 

![screenshot_20151027-225644](https://cloud.githubusercontent.com/assets/416166/10773838/12fb27cc-7cfe-11e5-9ec9-02f11fcbf678.png)

**Comment by breadcan** [comment]
It does work with 1.3.5 with the same json.
I guess it is something wrong in 1.4-alpha2 with the URL parsing which results in HTTP 503 and sometimes 400 coming back from the Streaming Servers.
I tried remove the parameters at the end of the URL but same case. Maybe the @ in the URL is the problem in the new version? Or maybe the m3u8 contains some stuff the new version can't understand.


btw, when I uninstall 1.3.5 and install 1.4-alpha2 the google drive integration seems broken (it always say something about invalid file, even with its own created one). It works when I do an inplace upgrade from 1.3.5 to 1.4-alpha2.

**Comment by Fleker** [comment]
Thanks for letting me know. I'll test it out myself. If something did
change in the past few builds then I should be able to fix it.

**Comment by Fleker** [comment]
I've been looking at this and I agree it definitely should work. It works on VLC player on both my phone and my laptop. 

It seems like, based on what I've done, that this stream is in the MPEG-TS format. This means it is supported by ExoPlayer, the integrated media player, but I think I'll need to change some stuff around.

**Comment by Fleker** [comment]
10-29 15:00:22.541 5280-5280/com.felkertech.n.cumulustv D/cumulus:TvInputPlayer: http://wdr_fs_geo-lh.akamaihd.net/i/wdrfs_geogeblockt@112044/index_3776_av-p.m3u8?sd=10&rebase=on
    10-29 15:00:22.541 5280-5280/com.felkertech.n.cumulustv D/cumulus:TvInputPlayer: http://wdr_fs_geo-lh.akamaihd.net/i/wdrfs_geogeblockt%40112044/index_3776_av-p.m3u8?sd=10&rebase=on

**Comment by Fleker** [comment]
Yeah, so here's the thing:

    final Uri uri = processUriParameters(originalUri, dataSource);

The player was doing some uri processing, obstensibly to validate the stream. This, unfortunately, meant that streams with unusual characters (such as a @) get transformed into a different set of characters (%40). So the new url becomes invalid and thus gives you a 503 error, because that url doesn't make sense.

I think this is a big part of what caused past streams to break as well. Every so often I've heard of a stream not working, but after this in-depth investigation I think this bug fix will be appreciated very much.

This will be published in the next build (tomorrow morning or so)

**Comment by breadcan** [comment]
Works fine now. Thanks.
