### ISSUE TITLE
Crashes on M without Storage Permission

### ISSUE THREAD

**Issue by bgiesing** [Fleker/CumulusTV#66]
It keeps crashing on me unless I go into Settings and manually enable the Storage permission that the app is supposed to ask to enable. 

@Fleker

**Comment by Fleker** [comment]
Odd. Is there ever a message requesting storage?

Storage is required for Drive I believe.

**Comment by bgiesing** [comment]
@Fleker Nope

**Comment by Fleker** [comment]
I'll work on the permission utils and it should be ready in the next build

**Comment by albertogasparin** [comment]
+1 on Android M. Proposed manual fix works btw. :wink:

**Comment by Fleker** [comment]
Yeah I've been seeing a lot of crashes recently. This is a high priority bug.
