### ISSUE TITLE
Crash on Android TV

### ISSUE THREAD

**Issue by breadcan** [Fleker/CumulusTV#68]
Upgrade from Alpha to 1.4.1, crash on app open.

E/AndroidRuntime(23044): FATAL EXCEPTION: main
E/AndroidRuntime(23044): Process: com.felkertech.n.cumulustv, PID: 23044
E/AndroidRuntime(23044): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object ref
erence
E/AndroidRuntime(23044):        at android.preference.PreferenceManager.getDefaultSharedPreferencesName(PreferenceManager.java:374)
E/AndroidRuntime(23044):        at android.preference.PreferenceManager.getDefaultSharedPreferences(PreferenceManager.java:369)
E/AndroidRuntime(23044):        at com.felkertech.n.boilerplate.Utils.SettingsManager.<init>(SettingsManager.java:49)
E/AndroidRuntime(23044):        at com.felkertech.n.ActivityUtils.readDriveData(ActivityUtils.java:216)
E/AndroidRuntime(23044):        at com.felkertech.n.tv.LeanbackFragment.onConnected(LeanbackFragment.java:321)
E/AndroidRuntime(23044):        at com.google.android.gms.common.internal.zzj.zzg(Unknown Source)
E/AndroidRuntime(23044):        at com.google.android.gms.common.api.zze.zzmH(Unknown Source)
E/AndroidRuntime(23044):        at com.google.android.gms.common.api.zze.onConnected(Unknown Source)
E/AndroidRuntime(23044):        at com.google.android.gms.common.api.zzg$2.onConnected(Unknown Source)
E/AndroidRuntime(23044):        at com.google.android.gms.common.internal.zzi$zzg.zznO(Unknown Source)
E/AndroidRuntime(23044):        at com.google.android.gms.common.internal.zzi$zza.zzc(Unknown Source)
E/AndroidRuntime(23044):        at com.google.android.gms.common.internal.zzi$zza.zzr(Unknown Source)
E/AndroidRuntime(23044):        at com.google.android.gms.common.internal.zzi$zzc.zznQ(Unknown Source)
E/AndroidRuntime(23044):        at com.google.android.gms.common.internal.zzi$zzb.handleMessage(Unknown Source)
E/AndroidRuntime(23044):        at android.os.Handler.dispatchMessage(Handler.java:104)
E/AndroidRuntime(23044):        at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(23044):        at android.app.ActivityThread.main(ActivityThread.java:5314)
E/AndroidRuntime(23044):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(23044):        at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(23044):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime(23044):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 

Wiped App Data and it works now.

**Comment by Fleker** [comment]
Weird bug. I think I might have a workaround ready for the next build.
