### ISSUE TITLE
No Leanback on Start

### ISSUE THREAD

**Issue by Fleker** [Fleker/CumulusTV#70]
Is there an issue with the warm welcome? Users will initially get the phone UI even on a TV.

**Comment by alanmcramer** [comment]
I keep getting the intro screens nearly everytime I launch.  I would prefer there to be no intro screens, and have a button in the menu that is like a help or support screen.

**Comment by Fleker** [comment]
That could be an odd bug if I messed up something there, which I'm pretty sure I have.

As for the intro screens, I do like them because most people don't understand how the app works and I'd like to give them that information up front. Maybe I can link back to it at a later point in case someone needs help.
