### ISSUE TITLE
Marshmallow permissions need to be the actual permission

### ISSUE THREAD

**Issue by Fleker** [Fleker/CumulusTV#75]
`Fatal Exception: java.lang.IllegalArgumentException: Unknown permission: android.permission-group.STORAGE`

Oops.

Will fix tomorrow.

**Comment by RaftingJack** [comment]
Use Manifest.permission.READ_EXTERNAL_STORAGE, do not use Manifest.permission_group.STORAGE

**Comment by RaftingJack** [comment]
I have encountered a similar situation, use Manifest.permission.READ_EXTERNAL_STORAGE, do not use Manifest.permission_group.STORAGE

**Comment by davidbalas123** [comment]
@RaftingJack What about permission_group.location? should I ask for both FINE_LOCATOIN and COURSE_LOCATION ? I DON'T KNOW :(
