### ISSUE TITLE
Changing channels sometimes hangs

### ISSUE THREAD

**Issue by alanmcramer** [Fleker/CumulusTV#76]
Using the up and down to change channels between live channels, sometimes hangs with the logo on screen, spinning circle and "The channel will be available soon." text.  This never seems to show the channel, unless you back out of the Live Channels app and go back into it.

**Comment by Fleker** [comment]
I'll look into this. Can you say what device you're using and what operating system version you're running? What other live channel apps do you have? I've run into some live channel issues as well that I've run into occasionally. I think it could be due to the platform itself.

**Comment by alanmcramer** [comment]
Only Cumulus TV is installed.
Asus Nexus Player, running Android 6.0 Build MRA58N.

**Comment by Fleker** [comment]
I might chalk this up to a bug within Live Channels or an Internet connection issue.

**Comment by Fleker** [comment]
This is a tuning timeout issue. It'll be fixed soon as it's fixed in ChannelSurfer 0.2.8
