### ISSUE TITLE
Shortcuts

### ISSUE THREAD

**Issue by Fleker** [Fleker/CumulusTV#80]
Let users add a stream to their launcher

**Comment by Fleker** [comment]
Android N adds new APIs for shortcuts

**Comment by Fleker** [comment]
Android N removes new APIs for shortcuts, although the idea still should be available.

**Comment by Fleker** [comment]
http://theblerg.net/post/2016/10/1/integrating-android-71s-launcher-shortcuts-into-your-app

**Comment by nisrulz** [comment]
if this is still open can i work on this ?

**Comment by Fleker** [comment]
Go ahead and do it.

**Comment by Fleker** [comment]
Added in 1.6.8
