### ISSUE TITLE
3 VEVO Music Streams

### ISSUE THREAD

**Issue by Fleker** [Fleker/CumulusTV#86]
From "http://stackoverflow.com/questions/10104301/hls-streaming-video-url-need-for-testing"

http://vevoplaylist-live.hls.adaptive.level3.net/vevo/ch1/appleman.m3u8 (LIVE TV)
http://vevoplaylist-live.hls.adaptive.level3.net/vevo/ch2/appleman.m3u8 (LIVE TV)
http://vevoplaylist-live.hls.adaptive.level3.net/vevo/ch3/appleman.m3u8 (LIVE TV)

**Comment by bgiesing** [comment]
@Fleker VEVO Channels should have their official branding. [See here for each channel's logos (may need to crop them).](http://swanslee.com/VEVO-TV)

Vevo Live 1 should be `VEVO TV Hits`, Live 2 should be `VEVO TV Flow`, and Live 3 should be `VEVO TV Nashville`.

**Comment by Fleker** [comment]
Thanks for pointing these out! I only knew of the streams, not what they
pointed to. Will be in the next release.
