### ISSUE TITLE
Android TV Stopped Syncing with Live Channels

### ISSUE THREAD

**Issue by billymcintosh** [Fleker/CumulusTV#90]
Cumulus is having difficulties integrating the channels into Live Channels.

It worked earlier with the suggested channels and a few m3u playlists. 

I cleared the data and cache to start afresh and now the playlist appears to be found by LC but nothing is saved to it. 

The message is always "Not set up" in the sources setup page.   I just installed Pluto TV to test if it was LC, but that is set up correctly. 

Uninstalled/reinstalled/restarted the machine. 

It's mentioned in another issue that the export function isn't yet complete - is this related to #41?

**Comment by Fleker** [comment]
It's a known issue with the current version. Reverting to 1.4.6 should
allow it to work. I'm working on a series of fixes which will fix it.

**Comment by redondogabriel** [comment]
Apk?

**Comment by billymcintosh** [comment]
Thanks for the quick response!  

Will replace the version.

**Comment by billymcintosh** [comment]
@redondogabriel check in releases https://github.com/Fleker/CumulusTV/releases 

Unfortunately, I don't think that version has resolved the issue.  I'll keep testing and report back.

**Comment by billymcintosh** [comment]
Imported again and it worked.

**Comment by Fleker** [comment]
I'm going to keep this open because it is currently an issue.

**Comment by billymcintosh** [comment]
No probs.  I'll jump in to help testing once released.

**Comment by Fleker** [comment]
I'm hoping to get a beta ready soon.

**Comment by bgiesing** [comment]
Could it be because the new Live Channel's version changed the setup process and UI/UX for adding channels, @Fleker?

**Comment by josuearisty** [comment]
@bgiesing 1.4.6 is working fine!

**Comment by Fleker** [comment]
No, it's definitely my fault.
1.4.6 and 1.5.0 seem to be syncing fine.

**Comment by josuearisty** [comment]
@Fleker is 1.5.0 version alredy avaliable?

**Comment by Fleker** [comment]
No, there's still a few issues. Syncing seems to work, but there's no playback or EPG.

**Comment by josuearisty** [comment]
Alright.

When will you add an option to add custom EPG? Is it possible? I wish to add epg to my channel list. Thanks for all.

**Comment by Fleker** [comment]
Support for XMLTV is hidden. I need to expose it for users and add it to
the EPG.

**Comment by redondogabriel** [comment]
Is the source updated to your current status of 1.5.0? So i can build it?

**Comment by Fleker** [comment]
It's in the 1.5 branch. Note that it may not build.

**Comment by redondogabriel** [comment]
Cool, thanks, you're really cool, we talked via reddit once, with an issue with my shield.

**Comment by Fleker** [comment]
Thanks I'm glad you said so. I try to be accessible and fix issues quickly.

**Comment by Fleker** [comment]
1.5.1 should fix this
