### ISSUE TITLE
CumulusTV Community

### ISSUE THREAD

**Issue by Fleker** [Fleker/CumulusTV#91]
I've been getting a number of emails and messages with common problems. I should create a community to forward people to so that users can work out issues in a central forum.

**Comment by redondogabriel** [comment]
Or a subreddit haha

**Comment by josuearisty** [comment]
What about xda? I think this is the place for app to become more popular!

**Comment by Fleker** [comment]
My initial thought is to use Google+ as that is a common place for Android users. A subreddit may not be a bad idea either, although I don't know how much control I get as a mod (especially for notification settings).

I don't know if XDA will allow me to have my own subforum just for this app.

**Comment by bgiesing** [comment]
@Fleker As a mod of a G+ community with almost 2,000 users. DON'T! As much as I love G+, moderating is near impossible.

**Comment by Fleker** [comment]
What would you recommend?

**Comment by bgiesing** [comment]
@Fleker Well a few options I would consider:

- Reddit: big userbase but "meh" moderation under reddit's rules
- MightyBell: more Social network like, full moderation control, freemium, posts can have full formatting with a Google Docs style editor
- NodeBB: self-hosted with complete control over everything and open source/free, major projects use it (like Jekyll, Popcorn Time (before shutdown), Notepad++, etc), expandable with themes and plugins, and much more. It can be freely hosted using https://oasis.sandstorm.io and people can sign in with their Sandstorm account (which is GitHub or Google sign in).

**Comment by bgiesing** [comment]
@Fleker well and considering this project was born from a Reddit idea, I think it works.

**Comment by Fleker** [comment]
https://www.reddit.com/r/cumulustv/
