### ISSUE TITLE
m3u logos feature request

### ISSUE THREAD

**Issue by josuearisty** [Fleker/CumulusTV#97]
When I add my whole m3u playlist, no logo url is added.

My m3u playlist has logos for all channels.

I wish you add logos from m3u playlist.

The code is this:

tvg-logo="logo url"

Cumulus could take this url and add it to "channel logo url".

What do you think?

**Comment by Fleker** [comment]
Yes this does not seem very difficult to add.

**Comment by josuearisty** [comment]
Excellent! I hope you please add it soon!

Thanks
